/*
 * PAIRS site logic — generated by tools/build-site.py from
 * design/PAIRS_Site.dc.html. Edit the design file (or this script), not this
 * file: a rebuild overwrites it.
 *
 * Content (mentors, students, projects, awards) is the design file's own data,
 * kept verbatim. Slide decks and methodology write-ups live in js/decks.js,
 * built from content/ by tools/build-content.py.
 */
const DECKS = (window.PAIRS_DECKS || {});
const METHODOLOGIES = (window.PAIRS_METHODOLOGIES || {});

function deckSlides(projectId) {
  const deck = DECKS[projectId];
  return (deck && deck.slides) || [];
}

// Actions offered in a project's detail panel, in the order they appear.
function projectLinks(project) {
  const links = [];
  if (deckSlides(project.id).length) links.push({ kind: "slides", label: "View slideshow" });
  if (METHODOLOGIES[project.id]) links.push({ kind: "doc", label: "Read methodology" });
  return links;
}

const MENTORS = [
  { id: "M-01", name: "Kashfi Rehan", title: "Program Director & Lead Mentor", scope: "Program direction · Sessions · Grading · One-on-ones", photo: R("mentor-kashfi", "uploads/Kashfi Rehan.JPG"), bio: "Hey! I'm a rising senior at the Bronx High School of Science. My research interests lie in machine learning techniques as applied to biochemical and immunology settings. In my free time, I love to play the harmonica or ukulele and eat gyros a lot!" },
  { id: "M-02", name: "Shahzeb Wali", title: "Director of Agentic AI Systems & Web Development", scope: "Agentic AI systems · Web development · One-on-ones", photo: R("mentor-shahzeb", "uploads/Shahzeb Wali.jpg"), bio: "Hello! I'm a current Senior at Bronx High School of Science. I have done a pre-internship at Citibank for AI development, built my own construction management platform, and I'm on the Model UN team. I hope you guys have a great time during PAIRS." },
  { id: "M-03", name: "Arian Akther", title: "Applied Specializations & Fields Mentor", scope: "ML specialization tracks · Applied-field pairing · One-on-ones", photo: R("mentor-arian", "uploads/Arian Akther.jpeg"), bio: "Hey! I'm a rising senior at the Bronx High School of Science. My research interests lie in molecular biology and microbiology settings. In my free time, I like reading manga and playing video games. I also love eating different foods!" },
  { id: "M-04", name: "Brandon Sweet", title: "Deep Learning Mentor", scope: "Deep learning · Sessions · Grading · One-on-ones", photo: R("mentor-brandon", "uploads/Brandon Sweet.jpeg"), bio: "Hi! My name is Brandon Sweet. I\u2019m a rising senior at Bronx Science pursuing Materials Science & Engineering with a bit of AI to help out. I enjoy bouldering in my free time." }
];

function R(id, fallback) { return (window.__resources && window.__resources[id]) || fallback; }
const AWARD_DESCRIPTIONS = {
  "Applied Impact Award": "Research with the strongest real-world significance, practical value, or current societal relevance.",
  "Technical Excellence Award": "Outstanding computational or theoretical & mathematical rigor, ML sophistication, engineering, or analytical depth.",
  "Scientific Rigor Award": "Exceptional experimental design, evaluation, reproducibility, and scientific methodology.",
  "Innovation Award": "The most original idea, novel interdisciplinary connection, or creative contribution.",
  "PAIRS Distinguished Scholar Award": "The strongest overall project, balancing originality, technical quality, execution, impact, and communication."
};
const TRACKS = ["Computer Vision", "NLP", "Clustering / PCA", "Graph Neural Nets", "Regression", "Time Series"];

// The curriculum as taught, one entry per live session topic, so the
// Specializations and Applied Fields panels show the whole summer rather than
// only the techniques a project happened to pick up.
const TAUGHT_METHODS = [
  "Regression", "Clustering & PCA", "Unsupervised Learning", "Neural Networks",
  "Computer Vision", "Natural Language Processing", "Reinforcement Learning",
  "Time Series", "Ensemble Learning", "Graph Neural Networks", "Neural ODEs",
  "Recommendation Systems", "Knowledge-Informed Learning",
  "Physics-Informed Neural Networks", "Causal ML", "Survival Analysis",
  "Neuromorphic Computing", "Explainability & Interpretability"
];
const TAUGHT_FIELDS = [
  "Education", "Medicine", "Genomics", "Structural Biology", "Climate",
  "Aerospace", "Automotive", "Robotics", "Electronics",
  "Mechanical Engineering", "Sports Analytics", "Media"
];
const STUDENTS = [
  { name: "Dennis Zhuo", photo: R("st-01", "uploads/Dennis Zhuo.jpg"), bio: "I'm not a very sporty person but enjoy badminton and handball quite often. You'll also find me fixated on word or logic games. I listen to music that makes me question my identity." },
  { name: "Arthur Zin", photo: R("st-02", "uploads/Arthur Zin.png"), bio: "" },
  { name: "Khandaker Tamim", photo: R("st-03", "uploads/Khandaker Tamim.png"), bio: "Salutations! My name is Khandaker, and I have a deep passion for mathematics and computers. I also like spending my free time taking long walks at Orchard Beach." },
  { name: "Alexander Soll", photo: R("st-04", "uploads/Alexander Soll.jpg"), bio: "My name is Alexander Soll and I'm a rising 10th grader. I'm interested in chess, computer science and astrophysics, and I want to start doing some machine learning projects." },
  { name: "Tirtha Saha", photo: R("st-05", "uploads/Tirtha Saha.png"), bio: "Hi! I'm interested in computer science, programming, and the integration between machine learning and astronomy. Among other things, I like robotics, playing soccer, and reading books. I aspire to make the world a better place by solving complex, global problems through innovative and data-driven technologies." },
  { name: "Rehan Hashem", photo: R("st-06", "uploads/Rehan Hashem.png"), bio: "Current rising senior @ The Bronx High School Of Science. I am Bengali and reside in the Bronx. Soccer is one of my biggest passions and I would like to use machine learning and apply it to soccer. I also enjoy eating food, whether it's spicy, crunchy or tasty overall." },
  { name: "Muhayminul Haque", photo: R("st-07", "uploads/Muhayminul Haque.jpg"), bio: "Hello, I am a student of PAIRS. I like to play guitar and read books!" },
  { name: "Jahidur Rahat", photo: R("st-08", "uploads/Jahidur Rahat.jpg"), bio: "I am someone who has many interests, including machine learning, which I've been fascinated with ever since I was a kid." },
  { name: "Wilson Shao", photo: R("st-09", "uploads/Wilson Shao.jpg"), bio: "Hey, I'm Wilson Shao, and I am delighted with the opportunity to apply machine learning to my own project, preferably something related to aerospace. As you can tell by my project field, I have a great interest in aerospace engineering and plan to model some of my own planes soon. During my free time, I like going out to the gym to work out, playing badminton, playing volleyball, and various other sports." },
  { name: "Ishan Karmakar", photo: R("st-10", "uploads/Ishan Karmakar.png"), bio: "What's up y'all! Ishan here and a student of Pairs Summer 2026. I like Sushi, Embedded Systems, going out, and having fun." },
  { name: "Areeb Ahmed", photo: R("st-11", "uploads/Areeb Ahmed.jpg"), bio: "Hi, my name is Areeb. I am a student from Bronx Science and I live in Queens. I have great interests in STEM, especially areas related to engineering. Outside of school, I enjoy playing soccer with my friends." },
  { name: "Sumit Deb", photo: R("st-12", "uploads/Sumit Deb.png"), bio: "I like to play soccer and I want to major in mechanical engineering." },
  { name: "Wasi Hossain", photo: R("st-13", "uploads/Wasi Hossain.jpg"), bio: "Hello, my name is Wasi Hossain. I am a rising senior at Brooklyn Technical High School. I have a passion for robotics as it helps me pursue my dream of being an engineer. I love solving problems and learning new things. Learning about machine learning and incorporating my previous knowledge was really fun." },
  { name: "Ethan Tan", photo: R("st-14", "uploads/Ethan Tan.jpg"), bio: "Student at Bronx High School of Science. 2028'" },
  { name: "Rishav Banik", photo: R("st-15", "uploads/Rishav Banik.jpg"), bio: "Hello, I am Rishav Banik a senior from the Bronx High School of Science. I participate in various activities related to coding and engineering such as preparing for physics and engineering events in Science Olympiad, coding graphics engines, as well as building AI powered nerf turrets. I look forward to integrating AI into chip design to automate optimizing power and performance of future chips." }
];

const PROJECTS = [
  { id: "P-01", year: "2026", title: "AI Detection Ensemble: DistilBERT, Ghostbusters & Binoculars", blurb: "An ensemble AI-text detector combining DistilBERT, Ghostbusters, and Binoculars, tested with both linear and random-forest meta-classifiers.", method: "Natural Language Processing", field: "Education", team: "Ethan Tan, Arthur Zin, Dennis Zhuo", image: R("pc-01", "uploads/covers/P-01.png"), sourceFile: R("ps-01", "uploads/AI Detection Ensemble Model Based on DistillBERT, Ghostbusters, and Binoculars Final Presentation.pptx"), award: "Scientific Rigor Award", awardIcon: R("award-rigor", "uploads/award-scientific-rigor.png"), abstract: "Commercial AI detectors typically rely on a single signal and can be biased toward false positives or false negatives. This project combines three detection methods \u2014 DistilBERT, Ghostbusters, and Binoculars \u2014 into one ensemble, comparing a random-forest (LightGBM) meta-classifier against a standard logistic-regression one. Trained on short- and long-form human/AI text datasets and tested out-of-domain on the ELLIPSE corpus, the full ensemble reached about 99.16% accuracy. Ablations showed DistilBERT drove nearly all of that accuracy; Ghostbusters and Binoculars added little on in-domain text but held up far better than DistilBERT on ESL writing, where the full ensemble's accuracy collapsed." },
  { id: "P-02", year: "2026", title: "Reinforcement Learning for Robotic Arm Stabilization", blurb: "A Q-Learning controller trained to stabilize a weighted single-joint robotic arm, benchmarked against a threshold controller and a PID controller.", method: "Reinforcement Learning", field: "Robotics", team: "Ishan Karmakar", image: R("pc-02", "uploads/covers/P-02.png"), sourceFile: R("ps-02", "uploads/Ml slides.pptx"), award: "", abstract: "This project trains a Q-Learning controller to choose motor torque for a simulated single-joint robotic arm holding a 1kg weight, comparing it against a fixed threshold controller and a PID controller for how closely each holds the arm at its target angle. The simulation models gravity, motor torque, damping, and inertia, updating the arm's state every 0.01 seconds. The work is simulation-only; next steps include moving the trained controller onto physical hardware and testing a double-jointed arm." },
  { id: "P-03", year: "2026", title: "Physics-Informed LSTM Networks for Battery Remaining Useful Life", blurb: "An LSTM for predicting lithium-ion battery remaining useful life, with electrochemical aging physics embedded directly in the loss function.", method: "Physics-Informed Neural Networks", field: "Automotive", team: "Sumit Deb", image: R("pc-03", "uploads/covers/P-03.png"), sourceFile: R("ps-03", "uploads/battery_rul_presentation (1).pptx"), award: "", abstract: "Predicting a battery's Remaining Useful Life lets manufacturers schedule maintenance and design safer packs before failure. This project embeds SEI-growth kinetics and Arrhenius temperature dependence into an LSTM's loss function, training on 11 NASA PCoE lithium-ion cells across three ambient-temperature groups. After fixing a zero-gradient bug in the physics loss term, every physics-informed variant beat the plain LSTM baseline, with the Arrhenius temperature-rate constraint alone giving the largest and most consistent improvement \u2014 a 29% RMSE reduction. Combining both physics terms did not improve on the Arrhenius-only model, showing the two constraints can compete rather than simply add together." },
  { id: "P-04", year: "2026", title: "Physics-Informed ML for Multi-Chemistry Battery Voltage Prediction", blurb: "A physics-informed framework aiming to predict battery voltage across multiple chemistries (LFP, NCA, NMC) instead of one at a time.", method: "Physics-Informed Neural Networks", field: "Automotive", team: "Wasi Hossain", image: R("pc-04", "uploads/covers/P-04.png"), sourceFile: R("ps-04", "uploads/Physics-Informed Machine Learning for Multi-Chemistry Battery Voltage Prediction.pptx"), award: "", abstract: "Accurate battery voltage prediction underlies state-of-charge and state-of-health estimation, but most existing models are built for a single battery chemistry. This project develops a physics-informed machine learning framework intended to generalize across chemistries such as LFP, NCA, and NMC, combining empirical data with electrochemical principles and testing transfer learning to new chemistries with limited data. As of this presentation, results are projected benchmarks from synthetic PyBaMM data rather than completed experiments; training and validation on real battery data are still ahead." },
  { id: "P-05", year: "2026", title: "Timescale-Aware Neural ODEs for 6-DOF Aircraft Dynamics", blurb: "A Neural ODE that separates an aircraft's fast rotational dynamics from its slower translational dynamics, tested on F-15 flight simulations.", method: "Neural ODEs", field: "Aerospace", team: "Wilson Shao", image: R("pc-05", "uploads/covers/P-05.png"), sourceFile: R("ps-05", "uploads/Timescale-Aware Neural ODEs for 6-DOF Aircraft Dynamics.pptx"), award: "Technical Excellence Award", awardIcon: R("award-tech", "uploads/award-technical-excellence.png"), abstract: "A single aircraft state mixes rapid rotational responses with much slower translational motion, and a standard Neural ODE represents both in one shared vector field. This project splits derivative predictions into fast and slow branches operating on the same full state and control input, testing whether that separation, rather than just scaling derivatives, improves trajectory prediction. Results come from a single simulated F-15 and a limited set of held-out maneuvers; the multiscale and multi-regime architectures were tested separately rather than combined." },
  { id: "P-06", year: "2026", title: "Can an Unsupervised Model Tell Flight Anomalies Apart?", blurb: "A Variational Autoencoder trained only on normal flights, tested on whether it can tell three distinct anomaly types apart without ever seeing a labeled failure.", method: "Unsupervised Learning", field: "Aerospace", team: "Areeb Ahmed", image: R("pc-06", "uploads/covers/P-06.png"), sourceFile: R("ps-06", "uploads/Areeb PAIRS Slideshow.pptx"), award: "", abstract: "Real flight anomalies are rare and expensive to label, so this project trains a Variational Autoencoder only on normal flights from the NASA DASHlink dataset and flags anomalies by how badly a flight reconstructs. Tested on 99,837 flights spanning four anomaly classes \u2014 the rarest 94 times rarer than normal \u2014 reconstruction probability drove nearly all of the model's ability to separate anomaly types; the variational term itself added little over a plain autoencoder. At an honest, leak-free detection threshold, the model still caught only about 22% of anomalies, against roughly 67% for a hindsight-optimal threshold." },
  { id: "P-07", year: "2026", title: "Predicting Electromagnetic Interference in Circuit Boards", blurb: "A Fourier-enhanced, domain-decomposed Physics-Informed Neural Network for faster electromagnetic interference simulation than traditional FDTD.", method: "Physics-Informed Neural Networks", field: "Electronics", team: "Rishav Banik", image: R("pc-07", "uploads/covers/P-07.png"), sourceFile: R("ps-07", "uploads/Predicting Electromagnetic Interference in Circuit Boards with Physics-Informed Neural Networks.pptx"), award: "Applied Impact Award", awardIcon: R("award-impact", "uploads/award-applied-impact.png"), abstract: "Predicting electromagnetic interference before a circuit board is built normally requires FDTD simulation, which is accurate but takes hours and must restart from scratch after every design change. This project builds a Physics-Informed Neural Network trained to satisfy Maxwell's equations directly, addressing two problems that make standard PINNs fail here: spectral bias smoothing out high-frequency waves, and sharp field discontinuities at copper-board material boundaries. Against FDTD ground truth, the trained PINN reached a relative L2 error of 6.8% while evaluating about 1.8 million points per second. About the researcher: Rishav Banik is a senior from the Bronx High School of Science. He works on coding and engineering projects including Science Olympiad physics and engineering events, coding graphics engines, and building AI-powered nerf turrets, and looks forward to integrating AI into chip design to automate power and performance optimization for future chips." },
  { id: "P-08", year: "2026", title: "Context-Gated Stacked Ensemble for Soccer Match Prediction", blurb: "A stacking ensemble for soccer match outcomes, with a novel context gate that lets the model weighting change match by match.", method: "Ensemble Learning", field: "Sports Analytics", team: "Rehan Hashem", image: R("pc-08", "uploads/covers/P-08.png"), sourceFile: R("ps-08", "uploads/Full_Project_Presentation (1).pptx"), award: "", abstract: "Ensemble methods combine models in different ways \u2014 bagging averages independent guesses, boosting corrects bias sequentially, and stacking learns which model to trust. This project builds toward a nested StackingClassifier for soccer match prediction, then introduces a context-gated ensemble that lets the blend of underlying models shift per match rather than staying fixed, normalized by softmax. At the time of this presentation, the methodology \u2014 prediction target, features, architecture, splits, tuning, and evaluation protocol \u2014 is fully locked, with runs not yet executed." },
  { id: "P-09", year: "2026", title: "Can AI Catch an Eye Disease from a Photo?", blurb: "A transfer-learning CNN that flags diabetic retinopathy from retinal photographs, aimed at assisting screening in under-resourced areas.", method: "Computer Vision", field: "Medicine", team: "Jahidur Rahat, Aditta Roy", image: R("pc-09", "uploads/covers/P-09.png"), sourceFile: R("ps-09", "uploads/PAIRS.pptx"), award: "", abstract: "Diabetic retinopathy is a leading cause of preventable vision loss, but grading retinal photographs by hand is slow and inconsistent between doctors. This project fine-tunes a pretrained CNN to classify retinal photographs as healthy or showing signs of disease, reaching about 95% accuracy against a roughly 51% naive baseline. The model produced more false negatives than false positives, the costlier mistake for a screening tool; next steps include grading severity on a 0-4 scale and adding Grad-CAM so clinicians can see what drove each prediction." },
  { id: "P-10", year: "2026", title: "PICASO: Physics-Informed Cross-Attention Solar Optimizer", blurb: "A CNN with cross-attention and explainability tooling for predicting M- and X-class solar flares from magnetograms.", method: "Computer Vision", field: "Climate", team: "Tirtha Saha, Alexander Soll", image: R("pc-10", "uploads/covers/P-10.png"), sourceFile: R("ps-10", "uploads/Tirtha Saha - Final Presentation Materials.pptx"), award: "Innovation Award", awardIcon: R("award-innov", "uploads/award-innovation.png"), abstract: "Large solar flares can disrupt Earth's communication and power systems and endanger astronauts, but traditional forecasting methods struggle with rapid, complex magnetic dynamics. PICASO trains a CNN on solar magnetograms and physical measurements to predict M- and X-class flares, using attention maps, Grad-CAM, and SHAP to keep the model's decisions interpretable rather than a black box. The model distinguished flare from non-flare regions (TSS of 0.62) but showed boundary shortcut learning at magnetogram edges rather than focusing fully on the Polarity Inversion Line where most flares actually originate, and relied more on tabular physical measurements than on the images themselves." },
  { id: "P-11", year: "2026", title: "Can We Predict What Goes Viral? A Graph-Based Look at TikTok", blurb: "A GraphSAGE-based GNN predicting TikTok engagement from how videos connect through shared creators, sounds, and hashtags.", method: "Graph Neural Networks", field: "Media", team: "Khandaker Tamim", image: R("pc-11", "uploads/covers/P-11.png"), sourceFile: R("ps-11", "uploads/Final - Can-We-Predict-What-Goes-Viral.pptx"), award: "PAIRS Distinguished Scholar Award", awardIcon: R("award-scholar", "uploads/award-distinguished-scholar-4854fcad.png"), abstract: "This project tests whether a video's popularity can be predicted from how it connects to other videos through shared creators, sounds, and hashtags, rather than from its own stats alone. A GraphSAGE-based GNN edged out a LightGBM baseline on prediction error across five random seeds, but lost on ranking \u2014 the metric that actually matters for deciding which videos to promote \u2014 because all models hedged toward the average instead of committing to a guess. The sample itself limited the conclusion: every video already had over 530,000 likes, making this a study of hits versus bigger hits rather than viral versus non-viral." },
  { id: "P-12", year: "2026", title: "Physics-Informed Neural Networks for 2D Steady-State Flow Past a Cylinder", blurb: "A mesh-free PINN solving steady Navier-Stokes flow past a cylinder from physics alone, with controlled ablations isolating which design choices matter.", method: "Physics-Informed Neural Networks", field: "Mechanical Engineering", team: "Muhayminul Haque", image: R("pc-12", "uploads/covers/P-12.png"), sourceFile: R("ps-12", "uploads/PAIRS_PINN_Cylinder_Flow.pdf"), award: "", abstract: "Traditional CFD solvers need a fine mesh and a long solve for every new geometry or flow condition. This project trains a Physics-Informed Neural Network to solve steady, incompressible 2D Navier-Stokes flow past a cylinder using only the governing PDE and boundary conditions \u2014 no labeled CFD data \u2014 then runs controlled ablations isolating whether the PDE loss term, a pressure anchor, and boundary-loss weighting each actually matter. Incompressible Navier-Stokes only constrains pressure gradients, so the network could otherwise drift by adding any constant to the pressure field; the project fixes this with a single Dirichlet reference point." }
];

class Component extends DCLogic {
  state = { tab: "home", modal: null, filter: "All", lightbox: null, doc: null };

  openLightbox(project) {
    const deck = DECKS[project.id];
    if (!deck || !deck.slides || !deck.slides.length) return;
    this.setState({ lightbox: { projectId: project.id, title: project.title, index: 0 } });
  }

  openDoc(project) {
    const doc = METHODOLOGIES[project.id];
    if (!doc) return;
    this.setState({ doc: { projectId: project.id } });
  }

  closeDoc() { this.setState({ doc: null }); }
  closeLightbox() { this.setState({ lightbox: null }); }
  lightboxStep(delta) {
    this.setState((s) => {
      if (!s.lightbox) return s;
      const total = deckSlides(s.lightbox.projectId).length || 1;
      return { lightbox: { ...s.lightbox, index: (s.lightbox.index + delta + total) % total } };
    });
  }
  lightboxNext() { this.lightboxStep(1); }
  lightboxPrev() { this.lightboxStep(-1); }

  boot() {
    if (this.booted) return;
    this.booted = true;
    this.onScroll = () => {
      const y = window.scrollY;
      if (this.textEl) this.textEl.style.transform = `translateY(${y * 0.28}px)`;
      if (this.textEl) this.textEl.style.opacity = String(Math.max(0, 1 - y / 620));
      if (this.gridEl) this.gridEl.style.transform = `translateY(${y * 0.12}px)`;
      this.scrollY = y;
    };
    window.addEventListener("scroll", this.onScroll, { passive: true });
    this.onMove = (e) => {
      this.mx = (e.clientX / window.innerWidth - 0.5) * 2;
      this.my = (e.clientY / window.innerHeight - 0.5) * 2;
    };
    window.addEventListener("pointermove", this.onMove, { passive: true });
    this.hunt();
  }

  hunt() {
    window.clearInterval(this.huntTimer);
    const tick = () => {
      try {
      this.textEl = document.getElementById("pairs-hero-text");
      this.gridEl = document.getElementById("pairs-hero-grid");
      const anchor = this.gridEl && this.gridEl.parentElement;
      const y = anchor ? Math.max(0, -anchor.getBoundingClientRect().top) : 0;
      this.scrollY = y;
      if (this.textEl) {
        this.textEl.style.transform = "translateY(" + (y * 0.28) + "px)";
        this.textEl.style.opacity = String(Math.max(0, 1 - y / 620));
      }
      if (this.gridEl) this.gridEl.style.transform = "translateY(" + (y * 0.12) + "px)";
      const cv = document.getElementById("pairs-hero-canvas");
      if (cv && cv !== this.canvasEl) { this.canvasEl = cv; this.startScene(); }
      if (!cv) this.canvasEl = null;
      } catch (e) {}
      };
    tick();
    this.huntTimer = window.setInterval(tick, 40);
  }



  componentWillUnmount() {
    window.removeEventListener("scroll", this.onScroll);
    window.removeEventListener("pointermove", this.onMove);
    window.clearInterval(this.drawTimer);
    window.clearInterval(this.huntTimer);
  }

  startScene() {
    const cv = this.canvasEl;
    if (!cv) return;
    window.clearInterval(this.drawTimer);
    const ctx = cv.getContext("2d");
    const layers = [6, 9, 9, 4];
    const nodes = [];
    const edges = [];
    let idx = 0;
    layers.forEach((count, li) => {
      const x = (li - (layers.length - 1) / 2) * 150;
      const start = idx;
      for (let i = 0; i < count; i++) {
        const ang = (i / count) * Math.PI * 2 + li * 0.6;
        const r = 92 + (i % 3) * 26;
        nodes.push({ x, y: Math.cos(ang) * r, z: Math.sin(ang) * r, li, phase: Math.random() * 6.28 });
        idx++;
      }
      if (li > 0) {
        const prevStart = start - layers[li - 1];
        for (let a = prevStart; a < start; a++)
          for (let b = start; b < start + count; b++)
            if (Math.random() < 0.32) edges.push([a, b, Math.random()]);
      }
    });

    const draw = () => {
      const t = window.performance.now();
      if (!cv.isConnected || cv !== this.canvasEl) { window.clearInterval(this.drawTimer); return; }
      const dpr = Math.min(2, window.devicePixelRatio || 1);
      const w = cv.clientWidth, h = cv.clientHeight;
      if (cv.width !== w * dpr) { cv.width = w * dpr; cv.height = h * dpr; }
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      ctx.clearRect(0, 0, w, h);

      const time = t * 0.00055;
      const ry = time + (this.mx || 0) * 0.35;
      const rx = Math.sin(time * 0.7) * 0.18 + (this.my || 0) * 0.22;
      const cx = w * 0.72, cy = h * 0.5 - (this.scrollY || 0) * 0.12;
      const fov = 620;
      const pts = nodes.map((n, i) => {
        const pulse = Math.sin(t * 0.0034 + n.phase);
        let x = n.x, y = n.y, z = n.z * (1 + pulse * 0.05);
        let x1 = x * Math.cos(ry) - z * Math.sin(ry);
        let z1 = x * Math.sin(ry) + z * Math.cos(ry);
        let y1 = y * Math.cos(rx) - z1 * Math.sin(rx);
        let z2 = y * Math.sin(rx) + z1 * Math.cos(rx);
        const s = fov / (fov + z2 + 460);
        return { sx: cx + x1 * s, sy: cy + y1 * s, s, z: z2, pulse };
      });

      edges.forEach(([a, b, seed]) => {
        const p = pts[a], q = pts[b];
        const fire = (Math.sin(t * 0.0026 + seed * 6.28) + 1) / 2;
        ctx.strokeStyle = `rgba(65,97,128,${0.05 + fire * 0.16})`;
        ctx.lineWidth = 0.6;
        ctx.beginPath();
        ctx.moveTo(p.sx, p.sy);
        ctx.lineTo(q.sx, q.sy);
        ctx.stroke();
        if (fire > 0.94) {
          const k = (fire - 0.94) / 0.06;
          ctx.fillStyle = "rgba(89,128,166,.85)";
          ctx.beginPath();
          ctx.arc(p.sx + (q.sx - p.sx) * k, p.sy + (q.sy - p.sy) * k, 2, 0, 6.29);
          ctx.fill();
        }
      });

      pts.forEach((p) => {
        const r = 3.6 * p.s;
        ctx.beginPath();
        ctx.arc(p.sx, p.sy, r + 3, 0, 6.29);
        ctx.strokeStyle = `rgba(29,31,32,${0.1 + p.s * 0.12})`;
        ctx.lineWidth = 0.7;
        ctx.stroke();
        ctx.beginPath();
        ctx.arc(p.sx, p.sy, r, 0, 6.29);
        ctx.fillStyle = `rgba(65,97,128,${0.45 + (p.pulse + 1) * 0.22})`;
        ctx.fill();
      });
    };
    this.drawTimer = window.setInterval(draw, 33);
    draw();
  }

  openModal(m) { this.setState({ modal: m }); }

  mentorModal(m) {
    return {
      kicker: "MENTOR · " + m.id,
      title: m.name,
      subtitle: m.title.toUpperCase(),
      body: m.bio || "Description to come. Mentors lead the live sessions, review submitted work, and hold one-on-ones through the week.",
      slotId: "m-" + m.id + "-lg",
      slotPhoto: m.photo || "",
      photoWrapClass: "blueprint",
      slotHint: "Drop " + m.name + "'s photo",
      hasMeta: true,
      meta: [
        { k: "ROLE", v: m.title },
        { k: "SCOPE", v: m.scope },
        { k: "COHORT", v: "Summer 2026" }
      ],
      hasAwards: false, awards: [], hasLinks: false, links: []
    };
  }

  studentModal(s, i) {
    const proj = PROJECTS.find((p) => p.team && p.team.includes(s.name));
    return {
      kicker: "STUDENT · S-" + String(i + 1).padStart(2, "0"),
      title: s.name,
      subtitle: proj ? proj.method.toUpperCase() : "TRACK TO COME",
      body: s.bio || "Description to come. This page collects the student's project, their specialization track, and every certificate or award earned through the program.",
      slotId: "s-" + i + "-lg",
      slotPhoto: s.photo,
      photoWrapClass: "blueprint",
      photoFit: "cover",
      photoBg: "transparent",
      slotHint: "Drop photo",
      hasMeta: true,
      meta: [
        { k: "COHORT", v: "Summer 2026" },
        { k: "TRACK", v: proj ? proj.method : "Track to come" },
        { k: "PROJECT", v: proj ? proj.title : "Project to come" }
      ],
      hasAwards: true,
      awards: proj ? [
        { name: "Certificate of Completion", detail: "PAIRS · SUMMER 2026 · 10 WEEKS", icon: "", hasIcon: false, iconMissing: true, slotId: "s-" + i + "-cert" },
        { name: proj.award || "Research Portfolio", detail: proj.award ? "AWARDED FOR " + proj.title.toUpperCase() : "ANNOTATED LITERATURE BASE", icon: (proj.award && proj.awardIcon) || "", hasIcon: !!(proj.award && proj.awardIcon), iconMissing: !proj.award, slotId: "s-" + i + "-badge" }
      ] : [
        { name: "Certificate of Completion", detail: "PAIRS · SUMMER 2026 · 10 WEEKS", icon: "", hasIcon: false, iconMissing: true, slotId: "s-" + i + "-cert" }
      ],
      hasLinks: !!(proj && projectLinks(proj).length),
      links: proj ? projectLinks(proj).map((l) => ({ label: l.label, onClick: () => l.kind === "doc" ? this.openDoc(proj) : this.openLightbox(proj) })) : []
    };
  }

  projectModal(p) {
    const awards = [{ name: "Certificate of Completion", detail: "PAIRS · SUMMER " + p.year, icon: "", hasIcon: false, iconMissing: true, slotId: "award-" + p.id + "-cert" }];
    if (p.award) awards.push({ name: p.award, detail: "COHORT " + p.year + " · JURIED BY MENTORS", icon: p.awardIcon || "", hasIcon: !!p.awardIcon, iconMissing: false, slotId: "award-" + p.id + "-badge" });
    return {
      kicker: "PROJECT · " + p.id,
      title: p.title,
      subtitle: p.method.toUpperCase() + " × " + p.field.toUpperCase(),
      body: p.abstract,
      slotId: "p-" + p.id + "-lg",
      slotPhoto: p.image || "",
      photoWrapClass: "blueprint",
      photoFit: "contain",
      photoBg: "#1d2d3d",
      photoFit: "contain",
      photoBg: "#1d2d3d",
      slotHint: "Drop project figure",
      hasMeta: true,
      meta: [
        { k: "YEAR", v: p.year },
        { k: "METHOD", v: p.method },
        { k: "FIELD", v: p.field },
        { k: "TEAM", v: p.team }
      ],
      hasAwards: true, awards,
      hasLinks: !!projectLinks(p).length,
      links: projectLinks(p).map((l) => ({ label: l.label, onClick: () => l.kind === "doc" ? this.openDoc(p) : this.openLightbox(p) }))
    };
  }

  renderVals() {
    this.boot();
    const tab = this.state.tab;
    const filter = this.state.filter;
    const filterNames = ["All", ...Array.from(new Set(PROJECTS.map((p) => p.method)))];
    const shown = filter === "All" ? PROJECTS : PROJECTS.filter((p) => p.method === filter);

    return {
      isHome: tab === "home", isMembers: tab === "members", isProjects: tab === "projects", isAwards: tab === "awards",
      onHome: tab === "home" ? "1" : "0",
      onMembers: tab === "members" ? "1" : "0",
      onProjects: tab === "projects" ? "1" : "0",
      onAwards: tab === "awards" ? "1" : "0",
      goHome: () => { this.setState({ tab: "home" }); window.scrollTo(0, 0); },
      goMembers: () => { this.setState({ tab: "members" }); window.scrollTo(0, 0); },
      goProjects: () => { this.setState({ tab: "projects" }); window.scrollTo(0, 0); },
      goAwards: () => { this.setState({ tab: "awards" }); window.scrollTo(0, 0); },

      stats: [
        { num: "10", unit: "WEEKS", label: "of guided research, June 29 – September 4" },
        { num: "3", unit: "SESS / WK", label: "live sessions every Monday, Wednesday and Friday" },
        { num: "1", unit: ": 1", label: "mentorship, personal meetings and project feedback" },
        { num: "30+", unit: "STUDENTS", label: "in the current cohort, working solo or in groups" },
        { num: "20", unit: "PROJECTS", label: "built and presented by this cohort" },
        { num: "1,200+", unit: "HRS", label: "of learning and independent research by students" },
        { num: "300+", unit: "HRS", label: "of live instruction and mentorship by mentors" }
      ],

      defs: [
        { num: "DEF.01", term: "Model", body: "A function with adjustable numbers inside it. Give it an input and it returns a guess. Training is how those numbers get set." },
        { num: "DEF.02", term: "Training data", body: "The examples the model learns from. Each one is an input paired with the answer you want back, and the model never sees anything else." },
        { num: "DEF.03", term: "Loss", body: "One number saying how wrong the guess was. Learning is the search for settings that make that number small." },
        { num: "DEF.04", term: "Generalization", body: "Doing well on data the model has never seen. Memorizing the training set is easy, and this is the part that actually matters." }
      ],

      pipeline: [
        { step: "STEP 01", title: "Frame", body: "Name the question and decide what a correct answer even looks like." },
        { step: "STEP 02", title: "Data", body: "Collect it, clean it, split it into training and test sets you never mix." },
        { step: "STEP 03", title: "Train", body: "Pick a model, minimize the loss, watch it fit the training examples." },
        { step: "STEP 04", title: "Evaluate", body: "Measure on held-out data. This is where overfitting shows itself." },
        { step: "STEP 05", title: "Iterate", body: "Change the features, the model or the question, and go back to step one." }
      ],

      // The curriculum, not a summary of the project list: the summer covered
      // specializations that no project ended up using. TAUGHT_* carries the
      // session topics; whatever a project used is folded in after, so a new
      // project can never introduce a tag the page then fails to show.
      methods: Array.from(new Set([...TAUGHT_METHODS, ...PROJECTS.map((p) => p.method)])),
      fields: Array.from(new Set([...TAUGHT_FIELDS, ...PROJECTS.map((p) => p.field)])),
      studentCount: STUDENTS.length,

      mentors: MENTORS.map((m) => ({
        ...m,
        slotId: "mentor-" + m.id,
        slotPhoto: m.photo || "",
        slotHint: "Drop photo",
        open: () => this.openModal(this.mentorModal(m))
      })),

      students: STUDENTS.map((s, i) => {
        const proj = PROJECTS.find((p) => p.team && p.team.includes(s.name));
        return {
          id: "S-" + String(i + 1).padStart(2, "0"),
          name: s.name,
          track: proj ? proj.method : "Track to come",
          projectTitle: proj ? proj.title : "",
          slotId: "student-" + i,
          slotPhoto: s.photo,
          slotHint: "Drop photo",
          open: () => this.openModal(this.studentModal(s, i))
        };
      }),

      awardsList: PROJECTS.filter((p) => p.award).map((p) => ({
        name: p.award,
        description: AWARD_DESCRIPTIONS[p.award] || "",
        icon: p.awardIcon || "",
        hasIcon: !!p.awardIcon,
        slotId: "awardslist-" + p.id,
        team: p.team,
        projectTitle: p.title,
        projectId: p.id,
        open: () => this.openModal(this.projectModal(p))
      })),

      projectCount: PROJECTS.length,
      filters: filterNames.map((f) => ({
        label: f,
        border: f === filter ? "#5980a6" : "rgba(29,31,32,.16)",
        bg: f === filter ? "#5980a6" : "transparent",
        color: f === filter ? "#f2f2f3" : "#5d5d60",
        pick: () => this.setState({ filter: f })
      })),
      projects: shown.map((p) => ({
        ...p,
        slotId: "proj-" + p.id,
        slotPhoto: p.image || "",
        slotHint: "Drop project figure",
        awardLine: p.award ? "★ " + p.award.toUpperCase() : "CERTIFICATE OF COMPLETION",
        open: () => this.openModal(this.projectModal(p))
      })),

      hasLightbox: !!this.state.lightbox,
      lightbox: this.lightboxVals(),
      hasDoc: !!this.state.doc,
      doc: this.docVals(),
      closeDoc: () => this.closeDoc(),
      closeLightboxHandler: () => this.closeLightbox(),
      lightboxNextHandler: () => this.lightboxNext(),
      lightboxPrevHandler: () => this.lightboxPrev(),

      hasModal: !!this.state.modal,
      modal: this.state.modal || { meta: [], awards: [], links: [], slotPhoto: "", photoFit: "cover", photoBg: "transparent" },
      closeModal: () => this.setState({ modal: null }),
      stop: (e) => e.stopPropagation()
    };
  }
}
// ---------------------------------------------------------------- viewer ---
Component.prototype.lightboxVals = function () {
  const empty = { title: "", hasText: false, hasImage: false, slideKicker: "", slideTitle: "", slideBody: [], slideClass: "", slideFoot: "", currentImage: "", position: 1, total: 1 };
  if (!this.state.lightbox) return empty;
  const { projectId, title, index } = this.state.lightbox;
  const slides = deckSlides(projectId);
  const slide = slides[index];
  if (!slide) return Object.assign({}, empty, { title });
  const body = (slide.body || []).filter(Boolean);
  return {
    title: title,
    hasImage: !!slide.image,
    hasText: !slide.image,
    currentImage: slide.image || "",
    slideKicker: projectId + " · " + (DECKS[projectId] ? DECKS[projectId].slides.length : 0) + " SLIDES",
    slideTitle: slide.title || title,
    slideBody: body,
    slideClass: body.length ? "" : "slide-cover",
    slideFoot: String(index + 1).padStart(2, "0") + " / " + String(slides.length).padStart(2, "0"),
    position: index + 1,
    total: slides.length
  };
};

Component.prototype.docVals = function () {
  if (!this.state.doc) return { kicker: "", title: "", subtitle: "", sections: [] };
  const doc = METHODOLOGIES[this.state.doc.projectId] || {};
  const project = PROJECTS.find((p) => p.id === this.state.doc.projectId);
  return {
    kicker: "METHODOLOGY · " + this.state.doc.projectId,
    title: doc.title || "Methodology",
    // The source filename is provenance, not a subtitle — name the project.
    subtitle: doc.authors || (project ? project.title : ""),
    sections: doc.sections || []
  };
};

// Keyboard: arrows page the slideshow, Escape closes the topmost overlay.
document.addEventListener("keydown", (e) => {
  const app = window.PAIRS_APP;
  if (!app) return;
  if (e.key === "Escape") {
    if (app.state.doc) return app.closeDoc();
    if (app.state.lightbox) return app.closeLightbox();
    if (app.state.modal) return app.setState({ modal: null });
    return;
  }
  if (!app.state.lightbox) return;
  if (e.key === "ArrowRight") { e.preventDefault(); app.lightboxNext(); }
  if (e.key === "ArrowLeft") { e.preventDefault(); app.lightboxPrev(); }
});

const root = document.getElementById("app");
const template = document.getElementById("app-template");
const app = new Component(root, template);
window.PAIRS_APP = app;

// Background scroll under a full-screen overlay is disorienting on touch.
const baseRender = app.render.bind(app);
app.render = function () {
  baseRender();
  const locked = !!(this.state.modal || this.state.lightbox || this.state.doc);
  document.body.classList.toggle("is-locked", locked);
};
app.mount();
