/* Generated by tools/build-content.py from content/decks/*.json — do not edit. */
window.PAIRS_DECKS = {
 "P-01": {
  "source": "AI Detection Ensemble Model Based on DistillBERT, Ghostbusters, and Binoculars Final Presentation.pptx",
  "title": "AI Detection Ensemble Model Based on DistillBERT, Ghostbusters, and Binoculars",
  "slides": [
   {
    "n": 1,
    "image": "uploads/slides/P-01/01.webp",
    "title": "",
    "body": []
   },
   {
    "n": 2,
    "image": "uploads/slides/P-01/02.webp",
    "title": "",
    "body": []
   },
   {
    "n": 3,
    "image": "uploads/slides/P-01/03.webp",
    "title": "",
    "body": []
   },
   {
    "n": 4,
    "image": "uploads/slides/P-01/04.webp",
    "title": "",
    "body": []
   },
   {
    "n": 5,
    "image": "uploads/slides/P-01/05.webp",
    "title": "",
    "body": []
   },
   {
    "n": 6,
    "image": "uploads/slides/P-01/06.webp",
    "title": "",
    "body": []
   },
   {
    "n": 7,
    "image": "uploads/slides/P-01/07.webp",
    "title": "",
    "body": []
   },
   {
    "n": 8,
    "image": "uploads/slides/P-01/08.webp",
    "title": "",
    "body": []
   },
   {
    "n": 9,
    "image": "uploads/slides/P-01/09.webp",
    "title": "",
    "body": []
   },
   {
    "n": 10,
    "image": "uploads/slides/P-01/10.webp",
    "title": "",
    "body": []
   },
   {
    "n": 11,
    "image": "uploads/slides/P-01/11.webp",
    "title": "",
    "body": []
   },
   {
    "n": 12,
    "image": "uploads/slides/P-01/12.webp",
    "title": "",
    "body": []
   },
   {
    "n": 13,
    "image": "uploads/slides/P-01/13.webp",
    "title": "",
    "body": []
   },
   {
    "n": 14,
    "image": "uploads/slides/P-01/14.webp",
    "title": "",
    "body": []
   },
   {
    "n": 15,
    "image": "uploads/slides/P-01/15.webp",
    "title": "",
    "body": []
   },
   {
    "n": 16,
    "image": "uploads/slides/P-01/16.webp",
    "title": "",
    "body": []
   },
   {
    "n": 17,
    "image": "uploads/slides/P-01/17.webp",
    "title": "",
    "body": []
   },
   {
    "n": 18,
    "image": "uploads/slides/P-01/18.webp",
    "title": "",
    "body": []
   },
   {
    "n": 19,
    "image": "uploads/slides/P-01/19.webp",
    "title": "",
    "body": []
   },
   {
    "n": 20,
    "image": "uploads/slides/P-01/20.webp",
    "title": "",
    "body": []
   },
   {
    "n": 21,
    "image": "uploads/slides/P-01/21.webp",
    "title": "",
    "body": []
   },
   {
    "n": 22,
    "image": "uploads/slides/P-01/22.webp",
    "title": "",
    "body": []
   },
   {
    "n": 23,
    "image": "uploads/slides/P-01/23.webp",
    "title": "",
    "body": []
   },
   {
    "n": 24,
    "image": "uploads/slides/P-01/24.webp",
    "title": "",
    "body": []
   },
   {
    "n": 25,
    "image": "uploads/slides/P-01/25.webp",
    "title": "",
    "body": []
   }
  ]
 },
 "P-02": {
  "source": "Ml slides.pptx",
  "title": "Reinforcement Learning for Robotic Arm Stabilization: How good will it be?",
  "slides": [
   {
    "n": 1,
    "image": "uploads/slides/P-02/01.webp",
    "title": "Reinforcement Learning for Robotic Arm Stabilization: How good will it be?",
    "body": []
   },
   {
    "n": 2,
    "image": "uploads/slides/P-02/02.webp",
    "title": "Background/Context for this Project",
    "body": []
   },
   {
    "n": 3,
    "image": "uploads/slides/P-02/03.webp",
    "title": "Project Goal…",
    "body": []
   },
   {
    "n": 4,
    "image": "uploads/slides/P-02/04.webp",
    "title": "How the Robotic Arm Simulation Works",
    "body": []
   },
   {
    "n": 5,
    "image": "uploads/slides/P-02/05.webp",
    "title": "How “Q-Learning” Works + How I used it",
    "body": []
   },
   {
    "n": 6,
    "image": "uploads/slides/P-02/06.webp",
    "title": "How “Q-Learning” Works + How I used it (pt.2)",
    "body": []
   },
   {
    "n": 7,
    "image": "uploads/slides/P-02/07.webp",
    "title": "How “Q-Learning” Works + How I used it (pt.3)",
    "body": []
   },
   {
    "n": 8,
    "image": "uploads/slides/P-02/08.webp",
    "title": "How “Q-Learning” Works + How I used it (pt.4)",
    "body": []
   },
   {
    "n": 9,
    "image": "uploads/slides/P-02/09.webp",
    "title": "Experimental Design and Comparison",
    "body": []
   },
   {
    "n": 10,
    "image": "uploads/slides/P-02/10.webp",
    "title": "Findings: Training Results",
    "body": []
   },
   {
    "n": 11,
    "image": "uploads/slides/P-02/11.webp",
    "title": "Findings: Training Results (pt. 2)",
    "body": []
   },
   {
    "n": 12,
    "image": "uploads/slides/P-02/12.webp",
    "title": "Findings: Controller Comparison",
    "body": []
   },
   {
    "n": 13,
    "image": "uploads/slides/P-02/13.webp",
    "title": "Side Controller 1: Threshold Controller",
    "body": []
   },
   {
    "n": 14,
    "image": "uploads/slides/P-02/14.webp",
    "title": "Side Controller 2: PID Controller",
    "body": []
   },
   {
    "n": 15,
    "image": "uploads/slides/P-02/15.webp",
    "title": "Findings: Metrics Comparison",
    "body": []
   },
   {
    "n": 16,
    "image": "uploads/slides/P-02/16.webp",
    "title": "Findings: Ablation Study",
    "body": []
   },
   {
    "n": 17,
    "image": "uploads/slides/P-02/17.webp",
    "title": "Discussion and Conclusion",
    "body": []
   },
   {
    "n": 18,
    "image": "uploads/slides/P-02/18.webp",
    "title": "Limitations + Future Work for the Project",
    "body": []
   },
   {
    "n": 19,
    "image": "uploads/slides/P-02/19.webp",
    "title": "References",
    "body": []
   },
   {
    "n": 20,
    "image": "uploads/slides/P-02/20.webp",
    "title": "THANKS!",
    "body": []
   }
  ]
 },
 "P-03": {
  "source": "battery_rul_presentation (1).pptx",
  "title": "Physics-Informed LSTM Networks for Remaining Useful Life Prediction in Lithium-Ion Batteries",
  "slides": [
   {
    "n": 1,
    "image": "uploads/slides/P-03/01.webp",
    "title": "Physics-Informed LSTM Networks for Remaining Useful Life Prediction in Lithium-Ion Batteries",
    "body": []
   },
   {
    "n": 2,
    "image": "uploads/slides/P-03/02.webp",
    "title": "Agenda",
    "body": []
   },
   {
    "n": 3,
    "image": "uploads/slides/P-03/03.webp",
    "title": "The Problem: When Will This Battery Fail?",
    "body": []
   },
   {
    "n": 4,
    "image": "uploads/slides/P-03/04.webp",
    "title": "Specialization & Field",
    "body": []
   },
   {
    "n": 5,
    "image": "uploads/slides/P-03/05.webp",
    "title": "Dataset: NASA PCoE Battery Data",
    "body": []
   },
   {
    "n": 6,
    "image": "uploads/slides/P-03/06.webp",
    "title": "End-to-End Pipeline",
    "body": []
   },
   {
    "n": 7,
    "image": "uploads/slides/P-03/07.webp",
    "title": "Model: LSTM + Physics-Informed Loss",
    "body": []
   },
   {
    "n": 8,
    "image": "uploads/slides/P-03/08.webp",
    "title": "Architecture Diagram",
    "body": []
   },
   {
    "n": 9,
    "image": "uploads/slides/P-03/09.webp",
    "title": "Evaluation Design",
    "body": []
   },
   {
    "n": 10,
    "image": "uploads/slides/P-03/10.webp",
    "title": "A Real Debugging Story",
    "body": []
   },
   {
    "n": 11,
    "image": "uploads/slides/P-03/11.webp",
    "title": "Results: Corrected Physics-Informed Models",
    "body": []
   },
   {
    "n": 12,
    "image": "uploads/slides/P-03/12.webp",
    "title": "What the Results Show",
    "body": []
   },
   {
    "n": 13,
    "image": "uploads/slides/P-03/13.webp",
    "title": "Limitations & Future Work",
    "body": []
   },
   {
    "n": 14,
    "image": "uploads/slides/P-03/14.webp",
    "title": "Conclusion",
    "body": []
   },
   {
    "n": 15,
    "image": "uploads/slides/P-03/15.webp",
    "title": "Thank You",
    "body": []
   }
  ]
 },
 "P-04": {
  "source": "Physics-Informed Machine Learning for Multi-Chemistry Battery Voltage Prediction.pptx",
  "title": "Physics-Informed Machine Learning for Multi-Chemistry Battery Voltage Prediction",
  "slides": [
   {
    "n": 1,
    "image": "uploads/slides/P-04/01.webp",
    "title": "Physics-Informed Machine Learning for Multi-Chemistry Battery Voltage Prediction",
    "body": []
   },
   {
    "n": 2,
    "image": "uploads/slides/P-04/02.webp",
    "title": "Research Motivation",
    "body": []
   },
   {
    "n": 3,
    "image": "uploads/slides/P-04/03.webp",
    "title": "The Problem – Why This Matters",
    "body": []
   },
   {
    "n": 4,
    "image": "uploads/slides/P-04/04.webp",
    "title": "Literature Gap – What's Missing",
    "body": []
   },
   {
    "n": 5,
    "image": "uploads/slides/P-04/05.webp",
    "title": "Research Question",
    "body": []
   },
   {
    "n": 6,
    "image": "uploads/slides/P-04/06.webp",
    "title": "Physics Foundation – Electrochemistry Basics",
    "body": []
   },
   {
    "n": 7,
    "image": "uploads/slides/P-04/07.webp",
    "title": "Methodology Overview",
    "body": []
   },
   {
    "n": 8,
    "image": "uploads/slides/P-04/08.webp",
    "title": "Dataset Strategy",
    "body": []
   },
   {
    "n": 9,
    "image": "uploads/slides/P-04/09.webp",
    "title": "Feature Engineering",
    "body": []
   },
   {
    "n": 10,
    "image": "uploads/slides/P-04/10.webp",
    "title": "Model Architectures",
    "body": []
   },
   {
    "n": 11,
    "image": "uploads/slides/P-04/11.webp",
    "title": "Preventing Circular Logic – A Critical Methodological Control",
    "body": []
   },
   {
    "n": 12,
    "image": "uploads/slides/P-04/12.webp",
    "title": "Evaluation Metrics & Validation Strategy",
    "body": []
   },
   {
    "n": 13,
    "image": "uploads/slides/P-04/13.webp",
    "title": "Expected Results – Projected Performance",
    "body": []
   },
   {
    "n": 14,
    "image": "uploads/slides/P-04/14.webp",
    "title": "Limitations & Challenges",
    "body": []
   },
   {
    "n": 15,
    "image": "uploads/slides/P-04/15.webp",
    "title": "Research Contribution & Significance",
    "body": []
   }
  ]
 },
 "P-05": {
  "source": "Timescale-Aware Neural ODEs for 6-DOF Aircraft Dynamics.pptx",
  "title": "Timescale-Aware Neural ODEs for 6-DOF Aircraft Dynamics",
  "slides": [
   {
    "n": 1,
    "image": "uploads/slides/P-05/01.webp",
    "title": "",
    "body": []
   },
   {
    "n": 2,
    "image": "uploads/slides/P-05/02.webp",
    "title": "",
    "body": []
   },
   {
    "n": 3,
    "image": "uploads/slides/P-05/03.webp",
    "title": "",
    "body": []
   },
   {
    "n": 4,
    "image": "uploads/slides/P-05/04.webp",
    "title": "",
    "body": []
   },
   {
    "n": 5,
    "image": "uploads/slides/P-05/05.webp",
    "title": "",
    "body": []
   },
   {
    "n": 6,
    "image": "uploads/slides/P-05/06.webp",
    "title": "",
    "body": []
   },
   {
    "n": 7,
    "image": "uploads/slides/P-05/07.webp",
    "title": "",
    "body": []
   },
   {
    "n": 8,
    "image": "uploads/slides/P-05/08.webp",
    "title": "",
    "body": []
   },
   {
    "n": 9,
    "image": "uploads/slides/P-05/09.webp",
    "title": "",
    "body": []
   },
   {
    "n": 10,
    "image": "uploads/slides/P-05/10.webp",
    "title": "",
    "body": []
   },
   {
    "n": 11,
    "image": "uploads/slides/P-05/11.webp",
    "title": "",
    "body": []
   },
   {
    "n": 12,
    "image": "uploads/slides/P-05/12.webp",
    "title": "",
    "body": []
   },
   {
    "n": 13,
    "image": "uploads/slides/P-05/13.webp",
    "title": "",
    "body": []
   },
   {
    "n": 14,
    "image": "uploads/slides/P-05/14.webp",
    "title": "",
    "body": []
   },
   {
    "n": 15,
    "image": "uploads/slides/P-05/15.webp",
    "title": "",
    "body": []
   },
   {
    "n": 16,
    "image": "uploads/slides/P-05/16.webp",
    "title": "",
    "body": []
   },
   {
    "n": 17,
    "image": "uploads/slides/P-05/17.webp",
    "title": "",
    "body": []
   },
   {
    "n": 18,
    "image": "uploads/slides/P-05/18.webp",
    "title": "",
    "body": []
   },
   {
    "n": 19,
    "image": "uploads/slides/P-05/19.webp",
    "title": "",
    "body": []
   },
   {
    "n": 20,
    "image": "uploads/slides/P-05/20.webp",
    "title": "",
    "body": []
   },
   {
    "n": 21,
    "image": "uploads/slides/P-05/21.webp",
    "title": "",
    "body": []
   },
   {
    "n": 22,
    "image": "uploads/slides/P-05/22.webp",
    "title": "",
    "body": []
   },
   {
    "n": 23,
    "image": "uploads/slides/P-05/23.webp",
    "title": "",
    "body": []
   },
   {
    "n": 24,
    "image": "uploads/slides/P-05/24.webp",
    "title": "",
    "body": []
   },
   {
    "n": 25,
    "image": "uploads/slides/P-05/25.webp",
    "title": "",
    "body": []
   }
  ]
 },
 "P-06": {
  "source": "Areeb PAIRS Slideshow.pptx",
  "title": "Can an Unsupervised Model Tell Flight Anomalies Apart?",
  "slides": [
   {
    "n": 1,
    "image": "uploads/slides/P-06/01.webp",
    "title": "Can an Unsupervised Model Tell Flight Anomalies Apart?",
    "body": []
   },
   {
    "n": 2,
    "image": "uploads/slides/P-06/02.webp",
    "title": "Primary Question:",
    "body": []
   },
   {
    "n": 3,
    "image": "uploads/slides/P-06/03.webp",
    "title": "THE DATASET",
    "body": []
   },
   {
    "n": 4,
    "image": "uploads/slides/P-06/04.webp",
    "title": "Class Imbalance",
    "body": []
   },
   {
    "n": 5,
    "image": "uploads/slides/P-06/05.webp",
    "title": "The Strategy: Learn Normal, Notice What Isn't",
    "body": []
   },
   {
    "n": 6,
    "image": "uploads/slides/P-06/06.webp",
    "title": "Ensuring Fairness",
    "body": []
   },
   {
    "n": 7,
    "image": "uploads/slides/P-06/07.webp",
    "title": "Two Design Questions We Tested",
    "body": []
   },
   {
    "n": 8,
    "image": "uploads/slides/P-06/08.webp",
    "title": "Results:",
    "body": []
   },
   {
    "n": 9,
    "image": "uploads/slides/P-06/09.webp",
    "title": "The β Ablation",
    "body": []
   },
   {
    "n": 10,
    "image": "uploads/slides/P-06/10.webp",
    "title": "Grouping Doesn't Help Uniformly",
    "body": []
   },
   {
    "n": 11,
    "image": "uploads/slides/P-06/11.webp",
    "title": "Major Findings",
    "body": []
   },
   {
    "n": 12,
    "image": "uploads/slides/P-06/12.webp",
    "title": "Some Limitations",
    "body": []
   },
   {
    "n": 13,
    "image": "uploads/slides/P-06/13.webp",
    "title": "In Conclusion..",
    "body": []
   },
   {
    "n": 14,
    "image": "uploads/slides/P-06/14.webp",
    "title": "Thank You",
    "body": []
   }
  ]
 },
 "P-07": {
  "source": "Predicting Electromagnetic Interference in Circuit Boards with Physics-Informed Neural Networks.pptx",
  "title": "Predicting Electromagnetic Interference in Circuit Boards with Physics-Informed Neural Networks",
  "slides": [
   {
    "n": 1,
    "image": "uploads/slides/P-07/01.webp",
    "title": "Predicting Electromagnetic Interference in Circuit Boards with Physics-Informed Neural Networks",
    "body": []
   },
   {
    "n": 2,
    "image": "uploads/slides/P-07/02.webp",
    "title": "The Problem",
    "body": []
   },
   {
    "n": 3,
    "image": "uploads/slides/P-07/03.webp",
    "title": "The Problem",
    "body": []
   },
   {
    "n": 4,
    "image": "uploads/slides/P-07/04.webp",
    "title": "What is a PINN",
    "body": []
   },
   {
    "n": 5,
    "image": "uploads/slides/P-07/05.webp",
    "title": "Why this is hard",
    "body": []
   },
   {
    "n": 6,
    "image": "uploads/slides/P-07/06.webp",
    "title": "Proposed Architecture",
    "body": []
   },
   {
    "n": 7,
    "image": "uploads/slides/P-07/07.webp",
    "title": "Methodology",
    "body": []
   },
   {
    "n": 8,
    "image": "uploads/slides/P-07/08.webp",
    "title": "Evaluation Metrics",
    "body": []
   },
   {
    "n": 9,
    "image": "uploads/slides/P-07/09.webp",
    "title": "Findings: The Training works",
    "body": []
   },
   {
    "n": 10,
    "image": "uploads/slides/P-07/10.webp",
    "title": "Findings: The Field",
    "body": []
   },
   {
    "n": 11,
    "image": "uploads/slides/P-07/11.webp",
    "title": "PINN vs FDTD",
    "body": []
   },
   {
    "n": 12,
    "image": "uploads/slides/P-07/12.webp",
    "title": "Limitations & Next Steps",
    "body": []
   },
   {
    "n": 13,
    "image": "uploads/slides/P-07/13.webp",
    "title": "Conclusion",
    "body": []
   }
  ]
 },
 "P-08": {
  "source": "Full_Project_Presentation (1).pptx",
  "title": "Context-Gated Stacked Ensemble for Soccer Match Prediction",
  "slides": [
   {
    "n": 1,
    "image": "uploads/slides/P-08/01.webp",
    "title": "Context-Gated Stacked Ensemble for Soccer Match Prediction",
    "body": []
   },
   {
    "n": 2,
    "image": "uploads/slides/P-08/02.webp",
    "title": "AGENDA",
    "body": []
   },
   {
    "n": 3,
    "image": "uploads/slides/P-08/03.webp",
    "title": "FOUNDATIONS",
    "body": []
   },
   {
    "n": 4,
    "image": "uploads/slides/P-08/04.webp",
    "title": "Foundations",
    "body": []
   },
   {
    "n": 5,
    "image": "uploads/slides/P-08/05.webp",
    "title": "FOUNDATIONS",
    "body": []
   },
   {
    "n": 6,
    "image": "uploads/slides/P-08/06.webp",
    "title": "FOUNDATIONS · DIAGRAM",
    "body": []
   },
   {
    "n": 7,
    "image": "uploads/slides/P-08/07.webp",
    "title": "FOUNDATIONS · DIAGRAM",
    "body": []
   },
   {
    "n": 8,
    "image": "uploads/slides/P-08/08.webp",
    "title": "FOUNDATIONS · DIAGRAM",
    "body": []
   },
   {
    "n": 9,
    "image": "uploads/slides/P-08/09.webp",
    "title": "Architecture",
    "body": []
   },
   {
    "n": 10,
    "image": "uploads/slides/P-08/10.webp",
    "title": "ARCHITECTURE",
    "body": []
   },
   {
    "n": 11,
    "image": "uploads/slides/P-08/11.webp",
    "title": "ARCHITECTURE · DATASET",
    "body": []
   },
   {
    "n": 12,
    "image": "uploads/slides/P-08/12.webp",
    "title": "ARCHITECTURE · FEATURES",
    "body": []
   },
   {
    "n": 13,
    "image": "uploads/slides/P-08/13.webp",
    "title": "ARCHITECTURE · MODELS",
    "body": []
   },
   {
    "n": 14,
    "image": "uploads/slides/P-08/14.webp",
    "title": "ARCHITECTURE · DIAGRAM",
    "body": []
   },
   {
    "n": 15,
    "image": "uploads/slides/P-08/15.webp",
    "title": "ARCHITECTURE · THE MATH",
    "body": []
   },
   {
    "n": 16,
    "image": "uploads/slides/P-08/16.webp",
    "title": "ARCHITECTURE · COMPARISON",
    "body": []
   },
   {
    "n": 17,
    "image": "uploads/slides/P-08/17.webp",
    "title": "Safeguards",
    "body": []
   },
   {
    "n": 18,
    "image": "uploads/slides/P-08/18.webp",
    "title": "SAFEGUARDS",
    "body": []
   },
   {
    "n": 19,
    "image": "uploads/slides/P-08/19.webp",
    "title": "SAFEGUARDS · PROTOCOL",
    "body": []
   },
   {
    "n": 20,
    "image": "uploads/slides/P-08/20.webp",
    "title": "SAFEGUARDS · EVALUATION",
    "body": []
   },
   {
    "n": 21,
    "image": "uploads/slides/P-08/21.webp",
    "title": "SAFEGUARDS · SCOPE",
    "body": []
   },
   {
    "n": 22,
    "image": "uploads/slides/P-08/22.webp",
    "title": "Code & Status",
    "body": []
   },
   {
    "n": 23,
    "image": "uploads/slides/P-08/23.webp",
    "title": "CODE",
    "body": []
   },
   {
    "n": 24,
    "image": "uploads/slides/P-08/24.webp",
    "title": "CODE · ROADMAP",
    "body": []
   },
   {
    "n": 25,
    "image": "uploads/slides/P-08/25.webp",
    "title": "",
    "body": []
   }
  ]
 },
 "P-09": {
  "source": "PAIRS.pptx",
  "title": "Can AI catch an Eye Disease from a Photo?",
  "slides": [
   {
    "n": 1,
    "image": "uploads/slides/P-09/01.webp",
    "title": "Can AI catch an Eye Disease from a Photo?",
    "body": []
   },
   {
    "n": 2,
    "image": "uploads/slides/P-09/02.webp",
    "title": "So... What Even Is This Disease?",
    "body": []
   },
   {
    "n": 3,
    "image": "uploads/slides/P-09/03.webp",
    "title": "Here's the Problem",
    "body": []
   },
   {
    "n": 4,
    "image": "uploads/slides/P-09/04.webp",
    "title": "What We Made",
    "body": []
   },
   {
    "n": 5,
    "image": "uploads/slides/P-09/05.webp",
    "title": "Quick Vocab Check",
    "body": []
   },
   {
    "n": 6,
    "image": "uploads/slides/P-09/06.webp",
    "title": "Where We Got Our Photos",
    "body": []
   },
   {
    "n": 7,
    "image": "uploads/slides/P-09/07.webp",
    "title": "Peeking at the Data",
    "body": []
   },
   {
    "n": 8,
    "image": "uploads/slides/P-09/08.webp",
    "title": "Prepping the Photos",
    "body": []
   },
   {
    "n": 9,
    "image": "uploads/slides/P-09/09.webp",
    "title": "Faking More Photos (Kind Of)",
    "body": []
   },
   {
    "n": 10,
    "image": "uploads/slides/P-09/10.webp",
    "title": "Inside the Model",
    "body": []
   },
   {
    "n": 11,
    "image": "uploads/slides/P-09/11.webp",
    "title": "Fixing an Unfair Split",
    "body": []
   },
   {
    "n": 12,
    "image": "uploads/slides/P-09/12.webp",
    "title": "Teaching It",
    "body": []
   },
   {
    "n": 13,
    "image": "uploads/slides/P-09/13.webp",
    "title": "Did It Even Learn?",
    "body": []
   },
   {
    "n": 14,
    "image": "uploads/slides/P-09/14.webp",
    "title": "Okay, But How Good Is It?",
    "body": []
   },
   {
    "n": 15,
    "image": "uploads/slides/P-09/15.webp",
    "title": "Where It Messed Up",
    "body": []
   },
   {
    "n": 16,
    "image": "uploads/slides/P-09/16.webp",
    "title": "The Good and the Bad",
    "body": []
   },
   {
    "n": 17,
    "image": "uploads/slides/P-09/17.webp",
    "title": "What's Next",
    "body": []
   },
   {
    "n": 18,
    "image": "uploads/slides/P-09/18.webp",
    "title": "Thank you! Questions?",
    "body": []
   }
  ]
 },
 "P-10": {
  "source": "Tirtha Saha - Final Presentation Materials.pptx",
  "title": "PICASO",
  "slides": [
   {
    "n": 1,
    "image": "uploads/slides/P-10/01.webp",
    "title": "PICASO",
    "body": []
   },
   {
    "n": 2,
    "image": "uploads/slides/P-10/02.webp",
    "title": "Introduction & Significance",
    "body": []
   },
   {
    "n": 3,
    "image": "uploads/slides/P-10/03.webp",
    "title": "Introduction & Significance Con’t",
    "body": []
   },
   {
    "n": 4,
    "image": "uploads/slides/P-10/04.webp",
    "title": "An AI can achieve high accuracy scores by simply guessing ‘quiet’",
    "body": []
   },
   {
    "n": 5,
    "image": "uploads/slides/P-10/05.webp",
    "title": "Model Description",
    "body": []
   },
   {
    "n": 6,
    "image": "uploads/slides/P-10/06.webp",
    "title": "Tabular Data",
    "body": []
   },
   {
    "n": 7,
    "image": "uploads/slides/P-10/07.webp",
    "title": "Tabular Data",
    "body": []
   },
   {
    "n": 8,
    "image": "uploads/slides/P-10/08.webp",
    "title": "Tabular Data",
    "body": []
   },
   {
    "n": 9,
    "image": "uploads/slides/P-10/09.webp",
    "title": "Data Processing",
    "body": []
   },
   {
    "n": 10,
    "image": "uploads/slides/P-10/10.webp",
    "title": "Model Architecture – Diagram",
    "body": []
   },
   {
    "n": 11,
    "image": "uploads/slides/P-10/11.webp",
    "title": "Model Architecture – Feature Extraction & Tokenization",
    "body": []
   },
   {
    "n": 12,
    "image": "uploads/slides/P-10/12.webp",
    "title": "Model Architecture – Asymmetric Fusion & Dual Head Inference",
    "body": []
   },
   {
    "n": 13,
    "image": "uploads/slides/P-10/13.webp",
    "title": "Results",
    "body": []
   },
   {
    "n": 14,
    "image": "uploads/slides/P-10/14.webp",
    "title": "Interpreting The Results:",
    "body": []
   },
   {
    "n": 15,
    "image": "uploads/slides/P-10/15.webp",
    "title": "Model Explainability",
    "body": []
   },
   {
    "n": 16,
    "image": "uploads/slides/P-10/16.webp",
    "title": "Model Explainability Con’t",
    "body": []
   },
   {
    "n": 17,
    "image": "uploads/slides/P-10/17.webp",
    "title": "Conclusion & Discussion",
    "body": []
   }
  ]
 },
 "P-11": {
  "source": "Final - Can-We-Predict-What-Goes-Viral.pptx",
  "title": "GNN-Based TikTok Engagement Prediction Using GraphSAGE and LightGBM",
  "slides": [
   {
    "n": 1,
    "image": "uploads/slides/P-11/01.webp",
    "title": "GNN-Based TikTok Engagement Prediction Using GraphSAGE and LightGBM",
    "body": []
   },
   {
    "n": 2,
    "image": "uploads/slides/P-11/02.webp",
    "title": "What I'll Cover",
    "body": []
   },
   {
    "n": 3,
    "image": "uploads/slides/P-11/03.webp",
    "title": "The Question, and What I Found",
    "body": []
   },
   {
    "n": 4,
    "image": "uploads/slides/P-11/04.webp",
    "title": "What Exactly Am I Predicting?",
    "body": []
   },
   {
    "n": 5,
    "image": "uploads/slides/P-11/05.webp",
    "title": "The Idea: Treat Videos as a Network",
    "body": []
   },
   {
    "n": 6,
    "image": "uploads/slides/P-11/06.webp",
    "title": "How the Graph Was Built",
    "body": []
   },
   {
    "n": 7,
    "image": "uploads/slides/P-11/07.webp",
    "title": "From Raw Data to a Prediction",
    "body": []
   },
   {
    "n": 8,
    "image": "uploads/slides/P-11/08.webp",
    "title": "The Experiment by the Numbers",
    "body": []
   },
   {
    "n": 9,
    "image": "uploads/slides/P-11/09.webp",
    "title": "Why This Is Hard: The Ingredients Are New",
    "body": []
   },
   {
    "n": 10,
    "image": "uploads/slides/P-11/10.webp",
    "title": "How I Tested It Fairly",
    "body": []
   },
   {
    "n": 11,
    "image": "uploads/slides/P-11/11.webp",
    "title": "Result 1: How Close Were the Numbers?",
    "body": []
   },
   {
    "n": 12,
    "image": "uploads/slides/P-11/12.webp",
    "title": "Result 2: Did It Rank the Right Videos?",
    "body": []
   },
   {
    "n": 13,
    "image": "uploads/slides/P-11/13.webp",
    "title": "Why Every Model Failed the Same Way",
    "body": []
   },
   {
    "n": 14,
    "image": "uploads/slides/P-11/14.webp",
    "title": "Cold-Start vs. Warm Videos",
    "body": []
   },
   {
    "n": 15,
    "image": "uploads/slides/P-11/15.webp",
    "title": "What Actually Mattered? (Ablation Study)",
    "body": []
   },
   {
    "n": 16,
    "image": "uploads/slides/P-11/16.webp",
    "title": "Is the Difference Real, or Just Luck?",
    "body": []
   },
   {
    "n": 17,
    "image": "uploads/slides/P-11/17.webp",
    "title": "What This Project Contributes",
    "body": []
   },
   {
    "n": 18,
    "image": "uploads/slides/P-11/18.webp",
    "title": "Limitations to Keep in Mind",
    "body": []
   },
   {
    "n": 19,
    "image": "uploads/slides/P-11/19.webp",
    "title": "Conclusion & What Others Should Do With It",
    "body": []
   },
   {
    "n": 20,
    "image": "uploads/slides/P-11/20.webp",
    "title": "Thank You",
    "body": []
   }
  ]
 },
 "P-12": {
  "source": "PAIRS_PINN_Cylinder_Flow.pdf",
  "title": "Physics-Informed Neural Networks for 2D Steady-State Flow Past a Cylinder",
  "slides": [
   {
    "n": 1,
    "image": "uploads/slides/P-12/01.webp",
    "title": "Physics-Informed Neural Networks for 2D Steady-State Flow Past a Cylinder",
    "body": []
   },
   {
    "n": 2,
    "image": "uploads/slides/P-12/02.webp",
    "title": "INTRODUCTION Why Teach a Neural Network Physics?",
    "body": []
   },
   {
    "n": 3,
    "image": "uploads/slides/P-12/03.webp",
    "title": "INTRODUCTION The Problem, and What We're Testing",
    "body": []
   },
   {
    "n": 4,
    "image": "uploads/slides/P-12/04.webp",
    "title": "METHODOLOGY Governing Physics and the PINN Loss",
    "body": []
   },
   {
    "n": 5,
    "image": "uploads/slides/P-12/05.webp",
    "title": "METHODOLOGY PINN Architecture & Training Loop",
    "body": []
   },
   {
    "n": 6,
    "image": "uploads/slides/P-12/06.webp",
    "title": "METHODOLOGY Experimental Design",
    "body": []
   },
   {
    "n": 7,
    "image": "uploads/slides/P-12/07.webp",
    "title": "FINDINGS Training Converges — But Plateaus Above Zero",
    "body": []
   },
   {
    "n": 8,
    "image": "uploads/slides/P-12/08.webp",
    "title": "FINDINGS Predicted Velocity Field",
    "body": []
   },
   {
    "n": 9,
    "image": "uploads/slides/P-12/09.webp",
    "title": "FINDINGS Predicted Pressure Field",
    "body": []
   },
   {
    "n": 10,
    "image": "uploads/slides/P-12/10.webp",
    "title": "FINDINGS — ABLATION 1 OF 3 The Pressure Anchor Fix Actually Works",
    "body": []
   },
   {
    "n": 11,
    "image": "uploads/slides/P-12/11.webp",
    "title": "FINDINGS — ABLATION 2 OF 3 Weighting the Boundary Loss Pays Off",
    "body": []
   },
   {
    "n": 12,
    "image": "uploads/slides/P-12/12.webp",
    "title": "FINDINGS — ABLATION 3 OF 3 Does the Physics Term Matter Here?",
    "body": []
   },
   {
    "n": 13,
    "image": "uploads/slides/P-12/13.webp",
    "title": "DISCUSSION & CONCLUSIONS What We Learned",
    "body": []
   },
   {
    "n": 14,
    "image": "uploads/slides/P-12/14.webp",
    "title": "LIMITATIONS & FUTURE WORK Where This Goes Next",
    "body": []
   },
   {
    "n": 15,
    "image": "uploads/slides/P-12/15.webp",
    "title": "APPENDIX Code & Key References",
    "body": []
   }
  ]
 }
};
window.PAIRS_METHODOLOGIES = {
 "P-05": {
  "source": "Multi-Regime Neural ODE For 6D Flight Dynamics (2).pdf",
  "title": "Multi-Regime Neural ODE For 6D Flight Dynamics",
  "authors": "",
  "sections": [
   {
    "heading": "2. Methods",
    "paragraphs": []
   },
   {
    "heading": "2.1 Problem Formulation",
    "paragraphs": [
     "We investigate the problem of learning a continuous-time dynamics model of a high-performance aircraft from trajectory data across varying environments. Here, the predicted state is represented by",
     "x(t) = [n, e, h, ϕ, θ, ψ, p, q, r, ub, vb, wb]⊤ ∈ R12   (1)",
     "where n, e, h denote inertial position, ϕ, θ, ψ denote Euler attitude angles, p, q, r denote body angular rates, and ub, vb, wb are body frame velocity vectors. The control vector is represented by",
     "uc(t) ∈ R4   (2)",
     "which includes the normalized aileron, elevator, rudder, and throttle commands. The body-frame velocity components are included since the aerodynamic response depends on both the speed and direction of the aircraft's motion. We use JSBSim to generate the ground-truth dynamics. The simulator evolves the state according to an ordinary differential equation (ODE):",
     "dx/dt = f(x, u)   (3)",
     "where f combines the rigid-body equations with aerodynamic forces and moments obtained from interpolated lookup tables. Our goal is to approximate f with a neural network fθ so that the trajectories obtained by integrating fθ from an initial state x(0) under a known control sequence u(t) reproduce the same ground-truth trajectories:",
     "This task's central difficulty is that high-performance flight dynamics often exhibit stiff, multi-timescale behavior, posing a challenge for Neural ODE learning. The body angular rates respond to control inputs within fractions of a second. Several aircraft responses occur on relatively short timescales, including short-period, Dutch-roll, and roll-subsidence behavior. The short period and Dutch roll oscillate with periods of roughly one to a few seconds. Roll subsidence damps out over a similar time interval, but it decays instead of oscillating. Meanwhile, position and speed change at a much slower scale, evolving over tens of seconds (phugoid, positional drift). The separation of timescales within a single state vector creates a challenging multi-timescale learning problem for a Neural ODE.",
     "The JSBSim F-15 model is treated as a controlled testbed for learning stiff, multi-timescale 6-DOF dynamics, with the prediction accuracy evaluated relative to the simulator."
    ]
   },
   {
    "heading": "2.2 Simulation Environment",
    "paragraphs": [
     "All training and evaluation datasets are generated with JSBSim 1.3.1, an open-source flight dynamics engine, using its bundled F-15 model. JSBSim integrates the full six-degree-of-freedom (6-DOF) rigid-body equations of motion at its native 120 Hz timestep, with the aerodynamic forces and moments obtained from coefficient lookup tables indexed by angle of attack, Mach number, and control-surface deflections.",
     "JSBSim was chosen over alternatives for a variety of reasons. First, JSBSim is headless and scriptable, allowing programmatic generation of thousands of trajectories that have randomized initial conditions and control inputs. Secondly, its dynamics are transparent. The equations of motion and aerodynamic tables are all inspectable, allowing us to determine the exact validity envelope of the aerodynamic model and enforce it during data generation through per-trajectory guards (Section 2.4). Lastly, JSBSim is a popular, established tool in aerospace simulation and reinforcement-learning literature. Unlike proprietary flight recorder and quick-access recorder (QAR) data used in many prior Neural-ODE flight dynamics work, JSBSim permits full public release of the generation code and data, making the benchmark easily reproducible from fixed random seeds.",
     "The bundled F-15 model used by JSBSim is an approximation constructed from public-domain data. This is sufficient for our purposes since the aircraft serves as a reproducible nonlinear 6-DOF testbed with stiff, multi-timescale behavior. Therefore, all reported model errors are evaluated relative to the trajectories generated by the simulator."
    ]
   },
   {
    "heading": "2.3 Data Generation",
    "paragraphs": [
     "Five datasets are generated using an identical trajectory protocol, with each dataset differing in one primary experimental axis relative to the baseline. Dataset A is the subsonic core used for primary single-regime comparison. Dataset B varies the flight regime, pushing the initial conditions into the transonic/supersonic range. Datasets C_high and C_low push the altitude to the high and low envelope edges of the F-15. Dataset D varies the aggressiveness of the maneuvers while staying in Dataset A's flight envelope. All datasets carry per-trajectory regime labels and generation metadata, permitting labeled concatenation at training time without loss of stratification (Table X).",
     "Each dataset consists of 1,000 trajectories. Each trajectory is simulated to be 15 seconds long and recorded at the native 120 Hz timestep. This yields 1,800 samples per run in a 21-column record: time, the 12 predicted flight dynamic states, four auxiliary variables, and the four control inputs. Each trajectory begins with the aircraft initialized in level flight and at a random altitude, Mach number, and heading. The aircraft is then trimmed to a steady-state equilibrium wherever a trim solution exists. In the case of a trim failure, which occurs predominantly at the thin-air envelope edge, the trajectory is retained and marked with a trim-failure flag. These flags are preserved as generation metadata for tracking trim success rates, but are not used to filter training or evaluation. Excitation is then applied as sampled maneuvers, with timing, amplitude, and width drawn independently per trajectory, and the resulting state evolution is recorded. Excitation widths range from 0.3- 1.2 s, corresponding to 9- 36 supervision intervals at the 30 Hz supervision rate, to ensure that control transitions are represented across multiple supervised samples. Engine throttle is fixed at its trim setting and held constant, with both engines running, for the duration of each run. Therefore, thrust-transient dynamics fall outside the scope of the dataset.",
     "Table 1. Stratified Dataset Design. Each dataset varies by one primary experimental axis relative to Dataset A, which acts as a baseline. All five share an identical trajectory pool of 15s at 120 Hz, giving 1800 samples per run.",
     "For datasets A-C, control excitation is designed to reveal the aircraft's characteristic dynamics without leaving the initial operating condition. Control excitation for Datasets A-C appears in the form of doublets. Doublets are a positive deflection held briefly, followed by an equal negative deflection before releasing. It is the standard system identification input in flight testing. They excite the characteristic modes while keeping the aircraft within its trimmed neighborhood. Inputs on the three axes are staggered in time within each trajectory so that each axis's response rings out separately. Dataset A trajectories consequently remain within approximately ±2 g and ≤25° bank, whereas Dataset D extends past these limits and reaches approximately 4.9 g and bank angles beyond 160°.",
     "Dataset D replaces doublets with an aggressive maneuver library. Each trajectory has one maneuver drawn, including sustained pulls, in which the elevator is held for several seconds; wind-up turns, which roll to a bank angle and then sustain a pull; roll captures, which hold large aileron deflections and rotate the aircraft through large bank angles, including past inverted; and multi-axis doublets, which overlap large-amplitude inputs on all axes.",
     "This design separates three distinct sources of difficulty that are often conflated. The first is timescale stiffness, which is present at every operating point and the subject of the core experiment. The second is the regime nonlinearity along the Mach axis, which dataset B is designed to probe as transonic drag rise produces sharp coefficient changes. The third is the state-space nonlinearity from aggressive maneuvers that Dataset D is designed to probe. Keeping these on separately labeled datasets allows the core architecture comparison to be unconfounded.",
     "The evaluation datasets probe three distinct extrapolation axes rather than a single ordering of difficulty. Datasets B and C are environmental extrapolations with their initial-condition boxes lying outside A's in Mach and altitude/air-density, respectively. In contrast, Dataset D shares A's environmental box but is the deepest state-space extrapolation due to its trajectories reaching angles of attack, load factors, and attitudes far beyond anything the training distribution contains. Dataset D is deliberately designed to operate closest to the aerodynamics model's validity boundary. Its angle-of-attack guard is limited to 18°, which is a 2° margin from the narrowest coefficient table's edge of 20°. Dataset D probes the most extreme dynamics the simulator can represent with full fidelity."
    ]
   },
   {
    "heading": "2.4 Fidelity enforcement",
    "paragraphs": [
     "Direct inspection of the F-15 aerodynamic tables shows that the narrowest coefficient table has a limited angle of attack range. When this limit is exceeded, JSBSim clamps the lookup to a boundary value, producing plausible-looking but frozen coefficients. To ensure the model stays truthful, we enforce validity during data generation. Dataset D monitors the angle of attack at every timestep and rejects any trajectory exceeding the allowed range of -15° to 18° (providing a 2° margin). This guarantees that no retained sample enters the clamped-table region. Additional guards are put in place to reject any trajectories that contain NaN/Inf values, Dataset A trajectories exceeding Mach 0.92 (preventing transonic effects from entering the subsonic core), Dataset Clow trajectories descending below 200 ft, and Dataset D trajectories descending below 500 ft. No explicit minimum-altitude guard is applied to Datasets A, B, or Chigh because their initial altitude ranges remain well above ground over the 15-second simulation horizon under the relatively mild doublet excitation. To mitigate early configuration errors, we abort generation if more than 30,000 attempts are needed to collect the 1,000 retained trajectories. All datasets use a fixed per-dataset random seed for reproducibility."
    ]
   },
   {
    "heading": "2.5 Preprocessing",
    "paragraphs": [
     "The datasets are split 70/15/15 into train/validation/test partitions at the trajectory level with stratification so that each regime contributes 700/150/150 trajectories. We avoid splitting at the timestep level because adjacent 120 Hz samples are nearly identical, which would leak training information into evaluation. We drop the time column and the four auxiliary variables before training, leaving only 12 predicted states and four controls. North and east position remain prediction targets but are removed from the input, leaving ten state inputs and four control inputs. Roll and heading are unwrapped before any derivatives are computed to remove the 2π discontinuities. Without this, the jump from 359° back to 0° registers as an enormous instantaneous yaw rate, which corrupts the finite-difference derivatives of ψ. Features are normalized using z-scores computed from the training partition only, and those statistics are stored for denormalization at evaluation.",
     "Training operates on short windows rather than full trajectories. Each sample is a 3-second (360-step) segment consisting of the initial state, the control sequence over the window, and the target state sequence. During training, states are supervised every fourth simulator sample (90 supervision points per 3-second window). Windows are drawn from random offsets each epoch to provide training samples without increasing storage. Final evaluation uses complete 15-second rollouts at the full 120 Hz resolution to measure the error that compounds over the long rollout horizon. The training-window length is fixed at 3 seconds across all final model comparisons.",
     "Figure 1. Data Generation and preprocessing. Trajectories are generated from randomized initial conditions, checked against aerodynamic feasibility, split by trajectory, normalized using training statistics, and sampled into 3-second training windows."
    ]
   },
   {
    "heading": "2.6 Models",
    "paragraphs": [
     "All models share the same interface. They are given an initial state x(0) and the control sequence u(t), and the model produces a predicted trajectory by using numerical integration of a learned vector field.",
     "Figure 2. Neural ODE forward pass. The numerical solver repeatedly queries the learned vector field fθ to advance the predicted state. Each query is counted as one function evaluation.",
     "Controls enter the vector field by piecewise-constant lookup at the solver's query time, matching the zero-order hold used during data generation.",
     "The baseline vector field is a three-hidden-layer multi-layer perceptron (MLP) with 128 nodes per layer and 36,492 parameters. It takes the ten state variables and four control inputs and produces derivatives for all 12 predicted states. A hyperbolic tangent (tanh) is used to provide a smooth learned vector field for numerical integration. The baseline width is fixed at 128 units to provide a compact reference architecture for the controlled comparisons below.",
     "A capacity-control ablation accompanies the baseline model. The same architecture is trained under an identical protocol, but at a substantially increased hidden width of 181 units with 70,783 parameters (twice that of the baseline). Its purpose is to test whether any advantage of the modified model comes from its structure rather than having greater model capacity. The state-scaled model uses the same MLP architecture as the baseline but adds a learnable output scale for each of the 12 derivatives. The scales are stored in logarithmic form so that they remain positive during training.",
     "The multiscale model partitions the state according to a hypothesized fast/slow timescale structure and organizes the learned vector field around that partition. There are two branches, each being a three-hidden-layer MLP of width 89 with tanh activations that receive the full 14-dimensional input. It has a fast branch that outputs the derivatives of attitude (φ, θ, ψ) and body rates (p, q, r). It has a slow branch that outputs the derivatives of position (n, e), altitude (h), and body-frame velocity (ub, vb, wb).",
     "Each of the 12 state derivatives gets its own learnable scale. We store each scale as a logarithm so it stays positive throughout the training. The initial values come from the data. For each state, the finite-difference derivative is taken across the training trajectories and its standard deviation is used to measure how fast that state typically changes. The branches write their outputs back into the standard state ordering, so the output looks identical to the baseline's from the outside. Both branches receive all ten inputs and all four controls. The split shapes what each branch produces, not information flow, since fast and slow dynamics are physically coupled. In total, the multiscale model has 35,802 parameters against the baseline's 36,492, a difference of 1.89%, with per-evaluation multiply-accumulate cost differing by 2.36%. A second multiscale configuration uses the same architecture and parameter count but assigns only the body rates (p, q, r) to the fast branch.",
     "Because the multiscale configuration retains the same learnable per-state derivative scaling used by the state-scaled model, the state-scaled architecture is used to isolate the effect of fast/slow branching. These two configurations differ only in which states are assigned to the fast branch.",
     "Figure 3. Multiscale Vector Field. The fast and slow branches receive the same state-control input but predict different subsets of the state derivatives. The outputs are scaled and reassembled into the full 12-dimensional derivative vector.",
     "For multi-regime training, two conditioned variants of the state-scaled architecture are trained on the combined A, B, Chigh, Clow datasets and receive an additional regime-conditioning signal. No gating network or separate regime experts are used. Instead, the same network is used across all regimes, with the conditioning signal changing how the vector field responds. Two conditioning methods are tested: a learned embedding of the discrete regime label and FiLM modulation. For the control baseline, a state-scaled model trained on the same combined dataset is used. This allows us to test whether explicitly providing regime information improves performance beyond simply training on a wider range of flight conditions.",
     "Figure 4. Multi-Regime Conditioning. Models are trained across datasets A, B, Chigh, Clow, with regime information supplied through either a learned embedding or FiLM modulation.",
     "Dataset D is excluded from the multi-regime training by design for two reasons. First, Dataset D is not a regime. It shares the same environmental box as Dataset A and only differs in maneuver aggressiveness. Therefore, a regime label for D would be uninformative about what distinguishes its trajectories. Conditioning on Dataset D would conflate the maneuver axis with the regime axis, negating the goal of the stratified design. Second, excluding Dataset D from all training preserves it as a pure held-out maneuver-generalization test for every model in the comparison."
    ]
   },
   {
    "heading": "2.7 Numerical Solvers",
    "paragraphs": [
     "A Neural ODE produces a trajectory by handing its learned vector field to a numerical solver, which integrates it forward through time. Therefore, every prediction costs many evaluations of fθ. For adaptive solvers, the number of evaluations depends on how difficult the learned dynamics are to integrate. All models are trained using fixed-step fourth-order Runge-Kutta (RK4). Final evaluation uses full-resolution RK4 with a timestep of (dt = 1/120)s matching the 120 Hz simulator sampling rate.",
     "To test whether the reported architecture comparisons depend on the numerical integration scheme, we perform a post-hoc solver robustness check on the baseline and rates-only multiscale configurations across five paired seeds. The same saved checkpoints are also reevaluated using RK4 at the standard timestep, RK4 with the timestep halved, and the adaptive Dormand-Prince method (DOPRI5). This check is used only to test numerical robustness and is not treated as a separate architecture-solver experiment. Training uses fixed-step RK4 with supervision applied every fourth simulator sample. Gradients are computed by backpropagation through the solver."
    ]
   },
   {
    "heading": "2.8 Training Protocol",
    "paragraphs": [
     "All models are trained using Adam with a learning rate of 10-3 and a batch size of 32, on randomly windowed 3-second segments. The optimizer is held fixed across comparisons. Training minimizes mean squared error between the integrated trajectory and the target over supervision points. The loss is computed in normalized coordinates:",
     "Here n indexes the N windows in a batch and m indexes the M supervision points within each window. A 3-second window supervised at every fourth timestep gives M = 90. During training, we supervise every fourth timestep, and during evaluation we use full resolution. Before any comparative experiment, every architecture must pass a single-trajectory overfit test, which requires a normalized rollout RMSE below 0.05 on a single memorized window, to verify the training machinery independently of its learning capacity.",
     "The primary experiment uses five paired random seeds, which control model initialization, training window selection, and data shuffling. As a post-primary robustness extension, the dataset A-trained core models are extended to ten total seeds, while the multi-regime models remain at five seeds. Results are reported using the mean and standard deviation across seeds, and with the individual seed values. Because corresponding configurations use the same random seed, comparisons between the architectures are evaluated using paired statistical tests. Hyperparameters shared across compared models are held constant within any comparison. These include the optimizer, learning rate, batch size, supervision density, and window length. Training uses validation-based early stopping with a minimum of 10 epochs and a patience of 15 epochs. The initial training ceiling was 120 epochs, and runs that reached this ceiling were continued to 160 epochs. The two runs that remained capped were continued to 190 epochs. All final runs ultimately termianted throught he early-stopping criterion rather than a hard epoch ceiling. Hyperparameters and model checkpoints are tuned on the validation partition only, with the test partition reserved for final reported numbers. [TBD: final epoch counts, schedules, and any early-stopping criteria from Phase 4.]"
    ]
   },
   {
    "heading": "2.9 Evaluation Metrics",
    "paragraphs": [
     "The main metric is per-timescale normalized RMSE, where rollout error is computed in the z-scored space to make the states comparable. Errors are reported separately for the fast group (p, q, r) and the slow group consisting of the remaining nine predicted states, rather than as a single aggregate.",
     "This separation prevents aggregate metrics from obscuring timescale-specific error.",
     "We report five supporting metrics:",
     "1. Aggregate normalized RMSE for comparability with work that does not separate timescales.",
     "2. Full 15-second rollout RMSE evaluated at the native 120 Hz resolution to measure error accumulation over the complete predicted horizon.",
     "3. Per-state normalized RMSE to identify which individual states drive differences in the fast, slow, and aggregate errors.",
     "4. Regime-stratified evaluation for the multi-regime models, with errors reported separately on each dataset. Dataset D is evaluated separately as a held-out maneuver-generalization test.",
     "5. A post-hoc numerical robustness check comparing the primary evaluation under RK4 at the standard timestep, RK4 with the timestep halved, and DOPRI5.",
     "Architecture comparisons use paired statistical tests across matching random seeds. Effect sizes are reported using paired Cohen's dz. We also report the number of seeds for which each model achieves a lower error. When several related comparisons are tested together, p-values are adjusted using the Holm procedure. To measure uncertainty from the finite test set, we also use paired trajectory-level bootstrapping. Here, whole test trajectories are resampled with replacement, using the same resampled indices for both models. Each regime contains 150 held-out trajectories while using 10,000 bootstrap resamples. For each sample, the rollout RMSE difference is recomputed with a 95% confidence interval.",
     "Figure 5. Evaluation Framework. Models are evaluated using full 15-second rollouts, fast-group, slow-group, aggregate, and per-state normalized RMSE, paired seed-level statistical comparisons, trajectory-level bootstrap confidence intervals, regime-stratified evaluation, and a post-hoc solver robustness check."
    ]
   },
   {
    "heading": "2.10 Experimental Design, comparisons, and ablations",
    "paragraphs": [
     "The core of the experiment is a controlled comparison in which exactly one main factor varies per contrast:",
     "Table 3. Model Configurations. Each adjacent pair differs by exactly one factor. The table identifies the model labels used throughout the results and the primary factor changed in each controlled comparison. Parameter counts are for the 14-dimensional input and 12-dimensional output.",
     "The experiments trained on Dataset A compare the baseline, capacity-control, state-scaled, and multiscale configurations. The contrast between the baseline and state-scaled model isolates the effect of the learnable per-state output scales. The capacity-control model tests whether any improvement is due to increased model capacity. Because the multiscale models also include the same learnable per-state derivative scaling, the state-scaled model isolates the additional effect of fast and slow branching. The comparison between the baseline and multiscale models compares the standard architecture against explicit fast and slow branching. Lastly, a second multiscale configuration changes only the branch partition, assigning only (p, q, r) to the fast branch to test whether restricting the fast pathway to body angular rates improves the timescale partition.",
     "The multi-regime comparison uses the same combined A, B, Chigh, Clow training data for its three configurations. The state-scaled model is used as an unconditioned control, while the other two models add a learned regime embedding and a FiLM conditioning, respectively. This allows the differences between the three models to be attributed to the conditioning mechanism rather than additional training data.",
     "Each contrast removes or changes a single component while holding the rest fixed, so the design works as a set of ablations without a separate ablation section. The capacity control comparison changes model size, the state-scaled comparison adds per-state output scaling, the state-scaled-to-multiscale comparison adds fast and slow branching, and the partition ablation changes which states are assigned to the fast branch. Dataset D is excluded from all training and is used only as a held-out maneuver-generalization test. The multi-regime comparisons add conditioning. Numerical sensitivity is instead assessed through the post-hoc solver robustness check."
    ]
   },
   {
    "heading": "2.11 Computation and Implementation",
    "paragraphs": [
     "All computation and implementation are done using PyTorch with torchdiffeq for differentiable ODE integration. Data generation, preprocessing, correctness tests, and development-scale training on roughly 300-trajectory subsets run on local CPU hardware. These small vector-field networks can be trained in a matter of minutes. Full-scale experiments and training are run on a rented single-GPU instance, an NVIDIA RTX 5090 with 32 GB of VRAM. These include the full multi-seed architecture comparisons, multi-regime training, and final rollout evaluations on the complete datasets. Each processed dataset is roughly 100 to 150 MB, small enough to fit in memory without streaming or sharding. GPU memory is consumed by solver depth and batch size rather than by dataset size.",
     "All generation, preprocessing, and training code is seed-fixed end to end. The code, seeds, and generated datasets are available on a publ"
    ]
   }
  ]
 },
 "P-12": {
  "source": "PINN_Cylinder_Flow_Methodology (1).pdf",
  "title": "Methodology: Physics-Informed Neural Network for 2D Steady-State Flow Past a Cylinder",
  "authors": "",
  "sections": [
   {
    "heading": "",
    "paragraphs": [
     "PAIRS Program Applied Field: Mechanical Engineering ML Specialization: Physics-Informed Neural Networks (PINNs)",
     "Revised Draft"
    ]
   },
   {
    "heading": "1 Chosen Algorithms/Architectures",
    "paragraphs": [
     "Model: A fully-connected feedforward Physics-Informed Neural Network, following Raissi, Perdikaris & Karniadakis (2019). Input: 2 neurons (x, y). Hidden layers: 8 layers, 20-40 neurons each, tanh activation (chosen for smooth, well-behaved higher-order derivatives, which matters since the PDE residual requires second derivatives via automatic differentiation). Output: 3 neurons (u, v, p). Weight initialization: Xavier/Glorot. Optimizer: Adam, followed by L-BFGS for final convergence refinement.",
     "Problem choice - flow past a cylinder, not lid-driven cavity: I deliberately chose flow past a cylinder over the lid-driven cavity problem. The cavity problem has a well-known pathology: the top two corners are geometric/boundary discontinuities where the wall velocity jumps instantaneously from 0 to the lid velocity. Because PINNs rely on automatic differentiation to compute smooth derivatives everywhere, this kind of true discontinuity causes the PDE residual loss to spike or become ill-defined near the corners, which can destabilize training. Flow past a cylinder has smooth boundaries and a smooth solution field everywhere (no true singularities at the Reynolds numbers I'm targeting), which makes it a much more appropriate first PINN project. I am consciously scoping the cavity problem out as a \"future work\" extension rather than attempting it now - handling boundary singularities properly (e.g., via localized loss weighting, corner-region point clustering, or excluding a small radius around the singular point) is a legitimate but separate research problem that would require its own methodology.",
     "Governing physics (steady, incompressible, 2D Navier-Stokes):",
     "u ∂u/∂x + v ∂u/∂y = −∂p/∂x + ν (∂²u/∂x² + ∂²u/∂y²)   (1)",
     "u ∂v/∂x + v ∂v/∂y = −∂p/∂y + ν (∂²v/∂x² + ∂²v/∂y²)   (2)",
     "∂u/∂x + ∂v/∂y = 0 (continuity)   (3)",
     "Target Reynolds number: Re ≈ 20-40, kept below the ~47 threshold where periodic vortex shedding begins, so the flow stays steady.",
     "Pressure anchoring (correction from earlier draft): Because incompressible Navier-Stokes only constrains pressure gradients, not absolute pressure, the system as written is under-determined - the network could add any constant offset to the entire predicted pressure field without violating any physics equation, and the PDE loss would never penalize it. To fix this, I will add a single-point Dirichlet condition anchoring the pressure scale: p = 0 at one fixed reference point, typically at the outlet (x_out, y_out), enforced as an additional term in the boundary loss. This removes the extra degree of freedom and ensures the network converges to a unique, physically meaningful pressure field rather than an arbitrarily shifted one.",
     "Loss function and weighting (revised):",
     "L_total = L_data + λ_BC · L_boundary + λ_PDE · L_phys   (4)",
     "Early in training, the physics/PDE residual loss (computed at thousands of interior collocation points) tends to dominate the boundary condition loss (computed at relatively few boundary points), which can cause the network to prioritize satisfying the PDE in the bulk fluid while underfitting the wall/inlet/outlet conditions - including the new pressure-anchor point. To address this, I will not use unweighted (λ = 1) loss terms. Instead I will:",
     "• Start with λ_BC set higher than λ_PDE (e.g., λ_BC = 10-100×, tuned empirically) so boundary conditions are enforced strongly from the start, and",
     "• Test a simple adaptive weighting scheme - such as periodically rescaling each loss term's weight based on the ratio of gradient magnitudes across loss terms (following Wang, Teng & Perdikaris, 2021) - so no single term dominates training throughout, not just at initialization.",
     "I will treat \"fixed high λ_BC\" as my baseline weighting strategy and \"adaptive weighting\" as an improvement I test and compare, rather than assuming one is correct in advance.",
     "Why this is the right theoretical fit: Flow past a cylinder is a well-posed, smooth boundary value problem with known governing equations - exactly the setting PINNs were designed for. Embedding the PDE and boundary/pressure-anchor constraints directly into the loss lets the network learn a continuous, mesh-free solution from far less labeled data than a purely data-driven model would need."
    ]
   },
   {
    "heading": "2 Data: Type, Source, and Size",
    "paragraphs": [
     "Primary data source (revised order of preference): Given that OpenFOAM is notoriously difficult to configure inside Google Colab (dependency issues, no native support, frequent need for Docker/manual builds), I am reordering my data plan by ease of implementation:",
     "1. First choice: Use Raissi et al.'s (2019) pre-computed, published cylinder wake dataset directly (https://github.com/maziarraissi/PINNs, cylinder nektar wake.mat) - real, high-fidelity spectral-element CFD data, already validated and widely cited, with zero setup risk. Note this dataset is technically the unsteady, vortex-shedding regime (Re ≈ 100); I will either (a) extract a representative time-slice as a steady approximation, or (b) adjust project scope slightly to include time as an input if I want to keep the true unsteady physics - I will decide this early and document the choice clearly, rather than mixing the two.",
     "2. Second choice, if I want full control over Reynolds number/geometry: Generate my own steady-state ground truth using a pure-Python solver such as scikit-fem or FEniCS, both of which install cleanly in Colab without the dependency headaches of OpenFOAM.",
     "3. Fallback attempt only: Try OpenFOAM if time allows and the above two options prove insufficient - I will time-box this attempt (e.g., a few hours) rather than let it become a bottleneck.",
     "Size: Whichever source I use, I expect a spatial mesh of roughly 5,000-20,000 points, each with (x, y, u, v, p) - a table of ~5,000-20,000 rows × 5 columns. As before, only a small fraction (1-5%, a few hundred points) will be used as labeled data for L_data; the rest serve as unlabeled collocation points for the PDE residual loss.",
     "EDA: Before training, I will visualize velocity/pressure contours and streamlines to confirm the flow field looks physically correct (recirculation zone behind the cylinder, no-slip at the wall), verify the flow is steady (or explicitly document that I'm using a time-slice of unsteady data, per above), and - if generating my own data - run a mesh-independence check to confirm the ground truth doesn't change meaningfully under further mesh refinement."
    ]
   },
   {
    "heading": "3 Preprocessing Steps",
    "paragraphs": [
     "• Non-dimensionalization: scale (x, y) by cylinder diameter D, (u, v) by free-stream velocity U∞, and pressure by ρU∞², keeping all network inputs/outputs on comparable numeric scales.",
     "• Collocation point sampling: Latin Hypercube Sampling (LHS) across the 2D domain for interior physics points.",
     "• Boundary point sampling: separate sampling along the cylinder surface, inlet, outlet, and far-field boundaries, since each carries a distinct condition - plus the single pressure-anchor point at the outlet described above.",
     "• No missing-value handling, resizing, or tokenization is needed, since this is continuous simulated/simulated-benchmark data, not images or text."
    ]
   },
   {
    "heading": "4 Feature Engineering / Selection",
    "paragraphs": [
     "Inputs remain simply (x, y) - the minimal, physically correct representation for this problem. The main transformation is non-dimensionalization. I may test adding a \"distance-from-cylinder\" auxiliary input as part of a later ablation, to see if it helps the network resolve the boundary layer near the wall faster, but this is not part of the base model."
    ]
   },
   {
    "heading": "5 Data Partitioning",
    "paragraphs": [
     "• Labeled points: 70% train / 15% validation / 15% test.",
     "• Collocation points: unlabeled, resampled fresh at intervals during training rather than split, since they carry no \"answer\" to overfit to.",
     "• Held-out spatial region: a portion of the domain (e.g., far wake) withheld entirely from training/collocation sampling, used only at the end to test generalization/extrapolation."
    ]
   },
   {
    "heading": "6 Class Imbalance",
    "paragraphs": [
     "Not applicable - this is a continuous regression/PDE-solving problem, not classification."
    ]
   },
   {
    "heading": "7 Hardware/Compute",
    "paragraphs": [
     "Google Colab with a free-tier GPU (T4) for PINN training. Ground-truth generation (if not using the pre-computed Raissi dataset) will use scikit-fem/FEniCS, both light enough to run in Colab or locally."
    ]
   },
   {
    "heading": "8 Software/Hardware Issues & Mitigations",
    "paragraphs": [
     "• Floating/undetermined pressure scale: resolved by the single-point pressure anchor described in Section 1 - without this, the model has infinitely many equally \"correct\" pressure solutions and won't converge meaningfully.",
     "• Loss term imbalance (PDE loss dominating boundary loss early in training): resolved by starting with a higher λ_BC and testing adaptive loss weighting (Section 1), rather than using unweighted loss terms as in the original draft.",
     "• Vanishing/exploding gradients from second-order derivatives: mitigated by moderate network depth and tanh activations.",
     "• OpenFOAM setup difficulty in Colab: deprioritized per the revised data plan in Section 2 - I will only attempt OpenFOAM as a time-boxed fallback, defaulting instead to the pre-computed dataset or scikit-fem/FEniCS.",
     "• Free-tier Colab session limits: mitigated with periodic model checkpointing so training can resume rather than restart."
    ]
   },
   {
    "heading": "9 Evaluation Metrics",
    "paragraphs": [
     "• Relative L2 error (standard PINN benchmark metric) for u, v, p separately.",
     "• RMSE and MAE in physical units, for interpretability.",
     "• R² to assess variance explained.",
     "• PDE residual magnitude - domain-specific metric measuring physical consistency independent of comparison to ground truth.",
     "• Mass-conservation check - ∮ (u·n) dS ≈ 0 across a closed contour, a physically meaningful sanity check specific to incompressible flow.",
     "• Pressure-field stability check (new): since pressure scale is now anchored, I will explicitly verify the predicted pressure field doesn't drift or exhibit an unphysical constant offset relative to ground truth - a direct check that the anchoring fix worked as intended.",
     "• Qualitative streamline/contour comparison plots against ground truth."
    ]
   },
   {
    "heading": "10 Baseline Model",
    "paragraphs": [
     "Baseline 1: Identical-architecture NN trained only on L_data (no physics loss term), isolating the physics term's contribution.",
     "Baseline 2: Published Raissi et al. (2019) PINN results, used as an external sanity-check reference for error magnitude."
    ]
   },
   {
    "heading": "11 Comparisons",
    "paragraphs": [
     "• CFD/benchmark ground truth (the reference all models are measured against).",
     "• A data-driven NN trained on substantially more labeled data, to illustrate the labeled-data efficiency trade-off the physics loss provides.",
     "• (Stretch goal) Gaussian Process Regression as a non-neural-network point of comparison."
    ]
   },
   {
    "heading": "12 Ablation Study (Revised/Scoped Down)",
    "paragraphs": [
     "My original ablation list (6 configurations) was too large to run rigorously with multiple seeds each in the available time. I'm scoping this down into a core set I will definitely run, plus a stretch set I'll attempt only if time allows:",
     "Core ablations (priority order):",
     "1. No PDE loss (data + boundary only) vs. full model - the most fundamental test of what the physics constraint contributes.",
     "2. No pressure anchor point vs. with anchor - directly demonstrates the floating-pressure problem described in Section 1 and justifies why the anchor is necessary.",
     "3. Fixed/unweighted loss (λ = 1 for all terms) vs. weighted/adaptive loss - directly tests whether the loss-weighting fix in Section 1 meaningfully improves convergence and boundary-condition satisfaction.",
     "Stretch ablations (time permitting):",
     "4. Varying labeled data amount (e.g., 10 vs. 100 vs. 1,000 points).",
     "5. Varying collocation point density.",
     "6. Network depth/width or activation function variation.",
     "I will run the core three with multiple random seeds each (to report mean ± standard deviation) before considering any stretch ablations, since a smaller number of well-run, well-documented comparisons is more valuable than a larger number of rushed ones."
    ]
   },
   {
    "heading": "13 Main Evaluation Study Design",
    "paragraphs": [
     "Independent variables: presence/absence of PDE loss, presence/absence of the pressure-anchor condition, loss weighting strategy (unweighted vs. fixed-weighted vs. adaptive), and (if reached) labeled data amount, collocation density, and architecture choices.",
     "Dependent variables: relative L2 error, RMSE, MAE, R² (u, v, p), PDE residual magnitude, mass-conservation error, and pressure-field offset/stability.",
     "Control group: the plain data-driven NN baseline (no physics loss).",
     "Experimental groups: each core ablation configuration in Section 12.",
     "Confounding factors controlled for:",
     "• Random seed/initialization: multiple runs per configuration (mean ± SD reported).",
     "• Optimizer/learning rate schedule: held constant unless it's the variable being tested.",
     "• Ground-truth accuracy: mesh-independence check (if self-generating data) so ground-truth error isn't mistaken for model error.",
     "• Collocation sampling randomness: seed fixed when comparing configurations not explicitly testing sampling itself.",
     "• Reynolds number: held fixed across all core comparisons.",
     "Revised based on feedback regarding singularity handling, pressure gauge freedom, loss-term balancing, ablation study feasibility, and CFD tooling risk. This version is designed to be more implementable within a Colab/student-project timeframe while remaining rigorous and comparable to established PINN literature (Raissi et al., 2019; Wang et al., 2021)."
    ]
   },
   {
    "heading": "References",
    "paragraphs": [
     "• Cai, S., Mao, Z., Wang, Z., Yin, M., & Karniadakis, G. E. (2022). Physics-informed neural networks (PINNs) for fluid mechanics: A review. Acta Mechanica Sinica. https://doi.org/10.1007/s10409-021-01148-1",
     "• Jin, X., Cai, S., Li, H., & Karniadakis, G. E. (2021). NSFnets (Navier-Stokes flow nets): Physics-informed neural networks for the incompressible Navier-Stokes equations. Journal of Computational Physics, 426, 109951. https://doi.org/10.1016/j.jcp.2020.109951",
     "• Karniadakis, G. E., Kevrekidis, I. G., Lu, L., Perdikaris, P., Wang, S., & Yang, L. (2021). Physics-informed machine learning. Nature Reviews Physics, 3(6), 422-440. https://doi.org/10.1038/s42254-021-00314-5",
     "• Kingma, D. P., & Ba, J. (2015). Adam: A method for stochastic optimization. arXiv. https://arxiv.org/abs/1412.6980",
     "• Paszke, A., Gross, S., Massa, F., Lerer, A., Bradbury, J., Chanan, G., Killeen, T., Lin, Z., Gimelshein, N., Antiga, L., Desmaison, A., Köpf, A., Yang, E., DeVito, Z., Raison, M., Tejani, A., Chilamkurthy, S., Steiner, B., Fang, L., ... Chintala, S. (2019). PyTorch: An imperative style, high-performance deep learning library. arXiv. https://arxiv.org/abs/1912.01703",
     "• Raissi, M., Perdikaris, P., & Karniadakis, G. E. (2019). Physics-informed neural networks: A deep learning framework for solving forward and inverse problems involving nonlinear partial differential equations. Journal of Computational Physics, 378, 686-707. https://doi.org/10.1016/j.jcp.2018.10.045",
     "• Raissi, M., Yazdani, A., & Karniadakis, G. E. (2020). Hidden fluid mechanics: Learning velocity and pressure fields from flow visualizations. Science, 367(6481), 1026-1030. https://doi.org/10.1126/science.aaw4741",
     "• Wang, S., Teng, Y., & Perdikaris, P. (2021). Understanding and mitigating gradient flow pathologies in physics-informed neural networks. SIAM Journal on Scientific Computing, 43(5), A3055-A3081. https://doi.org/10.1137/20M1318043",
     "• Raissi, M. (2019). PINNs [Cylinder wake dataset]. GitHub. https://github.com/maziarraissi/PINNs"
    ]
   }
  ]
 },
 "P-07": {
  "source": "Methodology.pdf",
  "title": "Methodology",
  "authors": "",
  "sections": [
   {
    "heading": "Methodology",
    "paragraphs": [
     "The improved architecture this paper develops is a Fourier-enhanced, domain-decomposed Physics-Informed Neural Network (PINN). It predicts electromagnetic interference (EMI) inside a printed circuit board (PCB), the layered board of copper and insulating material found in nearly every electronic device. The base architecture is a fully connected multilayer perceptron (MLP), the standard PINN backbone introduced by Raissi, Perdikaris, and Karniadakis [1]. The specific architecture this model enhances is the Extended Physics-Informed Neural Network (XPINN) [2], which splits the physical space into regions, each handled by its own network. This model builds on XPINN in two ways: adding per-subdomain Fourier feature embeddings inspired by Tancik et al. [3] and Wang and Perdikaris [4], and replacing XPINN's soft interface enforcement with a stronger mechanism at material boundaries.",
     "A PINN suits this problem for three reasons. First, Maxwell's equations are the governing physics, and a PINN builds them directly into training as a penalty term, pushing the network toward physically consistent predictions even where no reference data exists. In first-order time-domain form these are:",
     "∇ × E = −μ (∂H/∂t)          ∇ × H = ε (∂E/∂t) + σ_c E",
     "where E and H are the electric and magnetic fields, ε and μ are the permittivity and permeability of the material, and σ_c is its conductivity. Second, the problem requires evaluating the field at any point rather than only fixed grid locations; a PINN stores the solution in its weights as a continuous function, so once trained it can be queried anywhere at almost no cost, unlike grid solvers that need interpolation or a finer re-run. Third, a PINN extends naturally to inverse problems, learning unknown material properties alongside the weights, which a grid solver cannot do without wrapping many forward simulations in an outer loop.",
     "The predicted quantity is the full time-domain electromagnetic field: the three electric and three magnetic field components (Ex, Ey, Ez, Hx, Hy, Hz) as continuous functions of position and time. Stating this matters because \"predicting EMI\" can mean several things; some models predict frequency spectra, coupling between wire pairs, or radiated emissions. This project predicts the underlying field traveling through the copper traces and insulating layers of the PCB, from which those other quantities can be derived. The frequency range of interest is 1 to 10 GHz, covering modern high-speed digital connections. FR-4, the standard board insulator, has properties that vary slightly with frequency across this range; the current model treats them as fixed, a simplification a later model could remove.",
     "The decomposition follows the full three-dimensional material geometry, not only the vertical layer stack. A vertical-only split gives one network per layer but misses key physics, since the copper traces (the thin copper wires patterned onto the board) sit within a layer, and the strongest interference comes from in-plane structure such as coupling between neighboring traces and behavior at trace edges. Subdomain boundaries are therefore placed at every material transition, including the lateral edges of traces.",
     "The conditions at a boundary depend on its type. Between two insulators with no surface current, the fields are continuous across it, meaning the values on each side match:",
     "n × (E₁ − E₂) = 0          n × (H₁ − H₂) = 0",
     "At the surface of a conductor such as copper, the conditions differ. Copper conducts well, so the field inside effectively vanishes and it is standard to treat it as a perfect electric conductor. The tangential electric field is then zero at the surface, and the tangential magnetic field is discontinuous, with the jump equal to the surface current Js:",
     "n × E = 0          n × (H₁ − H₂) = Js",
     "Forcing the magnetic field to be continuous at a copper surface would tell the network there is no surface current, when those currents are the main source of the radiation being predicted. Copper regions are therefore treated as perfect-conductor boundaries rather than given their own networks, which also removes the instability caused by placing a very large conductivity value into the equations.",
     "Enforcing the interface conditions requires a mechanism, since two separate networks cannot agree exactly at a shared boundary unless the architecture forces them to. Three options exist: a heavily weighted penalty in the loss, which stays soft no matter how large the weight; an output transformation, where the raw output passes through a fixed layer built so the condition holds automatically; or parameter sharing, where both networks read the boundary value from one shared output. This project uses an output transformation for the perfect-conductor condition, multiplying the tangential electric field by a function that vanishes at the surface so n × E = 0 holds by construction. The insulator-to-insulator conditions currently use a strongly weighted penalty, which is soft; moving these to a shared parameterization is the main remaining design task, and results are reported with this limitation noted. The first-order form of Maxwell's equations is used because Nohra and Dufour [5] found it converges better on interface problems than the second-order form.",
     "The closest prior work, Nohra and Dufour [5, 6], also uses domain decomposition, but deliberately smooths over material discontinuities to avoid enforcing interface conditions. This project does the opposite, keeping boundaries sharp and enforcing conditions directly. Their approach trains more easily but loses accuracy in a thin band around each interface, while this one accepts harder training to keep that band accurate, since that region is where the interference originates. The two are opposite choices on the same problem, making theirs a direct comparison point.",
     "Standard networks suffer from spectral bias, learning smooth low-frequency patterns far faster than sharp high-frequency ones, a problem when the field oscillates quickly in space. Tancik et al. [3] showed that passing inputs through sine and cosine functions before the network corrects this. The embedding maps an input coordinate vector v as:",
     "γ(v) = [sin(2πBv), cos(2πBv)]",
     "where B is a fixed frequency matrix whose rows are drawn from a Gaussian with standard deviation σ_B. Using different frequency scales for different parts of a problem is not new; Wang and Perdikaris [4] introduced multi-scale Fourier embeddings, which motivate this approach. What is specific here is tying each region's scale to the wavelength in that region's material:",
     "λ = c / (f · √(εr μr))",
     "so a denser material, where the field oscillates faster, gets a higher-frequency embedding. Combining this scale-matching with spatial decomposition is the contribution: Wang and Perdikaris did the multi-scale part without decomposition, and XPINN did decomposition without scale-matching.",
     "This embedding is also the main feature engineering step. Instead of feeding raw coordinates to the network, each is expanded into a higher-dimensional set of sinusoidal features (128 per subdomain, from 64 frequency rows), which lets the network represent high-frequency field behavior. All six field components are predicted jointly; none are dropped and no dimensionality reduction is applied. The subdomain index acts as light feature selection, since each network sees only points within its own material region.",
     "Because the residual is small across most of the domain and concentrated near boundaries and sources, uniform sampling wastes effort. Residual-based adaptive refinement, proposed by Lu et al. [8], periodically scores a pool of candidate points by error and adds the worst; that work is credited here for the sampling method, not only the software library. Wu et al. [9] improved this with RAR-D, which samples points in proportion to their error rather than taking the strict worst, and which performs better, so RAR-D is used. Sampling runs independently within each subdomain to work with the per-region embeddings.",
     "No public dataset exists for this problem, so reference data is generated by finite-difference time-domain (FDTD) simulation, a standard grid-based method for solving Maxwell's equations. Ground-truth fields inside a 3D structure cannot be measured directly at fine resolution, so simulation is the accepted source of reference data. The solver is MEEP [7], an open-source FDTD package from MIT. The more common choice for board work is openEMS, so the reason for MEEP is practical: its native Python interface lets reference generation, sampling, and training run in one language with no conversion step, which matters when the solver is called repeatedly across geometries. MEEP also supports frequency-dependent materials, useful for the FR-4 extension noted above. Cross-checking against openEMS is future work.",
     "For each geometry the reference data is the six field components sampled on a grid over a sequence of time steps. For the baseline three-layer PCB stackup (a copper-insulator-copper sandwich, the simplest form of a real board), the grid is roughly 64 × 64 × 38 points across 21 time steps, about 3.2 million points and 19 million field values. Units are non-dimensionalized, a standard rescaling that sets the physical constants to one and keeps values in a stable range. Exploratory analysis guided several choices: field magnitude spans about three orders of magnitude, so inputs are normalized and loss terms weighted separately; early-training error clusters near interfaces and the source, justifying adaptive sampling; and the field is near zero inside copper, supporting the perfect-conductor treatment.",
     "Coordinates are normalized to [−1, 1] within each subdomain before the embedding, keeping the activation functions responsive; field values are used in normalized units. There are no missing values, images, or text to process, since the data comes from a deterministic solver on a complete grid, and no class imbalance to correct, since this is continuous regression rather than classification.",
     "The usual train-validation-test split does not apply cleanly, since most of the training signal comes from the physics penalty at unlabeled points. The split that exists is between the small set of reference points used in the loss and the rest held out: 2,000 points (under 0.1% of the grid) are drawn at random for the data term, and the full remaining grid is used only for final evaluation. Collocation points, where the physics penalty is checked, are sampled separately from the geometry: 8,192 per subdomain, plus smaller sets on the boundaries, initial time, and interfaces. K-fold cross-validation does not apply, since generalization here means covering a continuous domain rather than generalizing across separate samples.",
     "Training runs on a CUDA-capable GPU with automatic fallback to CPU. It is memory-intensive because the physics penalty requires differentiating through the networks, so reducing points per subdomain is the first step when memory is short, and candidate scoring is already chunked for this reason. MEEP installs through conda rather than pip and is awkward on Windows, so reference data is generated on Linux. PINN training can be unstable when penalty terms compete, handled with a two-phase schedule, Adam first for broad progress and L-BFGS second for fine convergence, plus fixed weights prioritizing the boundary and interface terms.",
     "Accuracy is measured against the held-out FDTD reference. The primary metric is relative L2 error per field component, the size of the error over the size of the true field:",
     "relative L2 error = ǁu_pred − u_trueǁ / ǁu_trueǁ",
     "This is standard, keeping results comparable to published work. Others are reported because relative L2 alone hides specific failures: mean squared error, for comparison with papers that use it; normalized root mean squared error, an easily read percentage; maximum absolute error, since a model can be accurate on average but badly wrong in a small important region; relative L2 error measured only near interfaces, directly testing the central claim; the physics residual on held-out points, checking whether the network satisfies Maxwell's equations where it never trained rather than memorizing data; and inference time per query against FDTD run time, measuring the practical speedup.",
     "The baseline is a standard PINN with no embedding, no decomposition, and uniform sampling, trained on the same geometry with the same size and budget. It is expected to perform poorly, and confirming it fails in the predicted way is part of the point, since the case for the architecture depends on the baseline genuinely struggling. Three published methods are also compared: a Fourier-only PINN with a single global scale, testing whether fixing spectral bias alone suffices; an XPINN with soft enforcement and no embedding, testing whether decomposition alone suffices; and a smoothed-interface PINN following Nohra and Dufour, testing the opposite interface choice. FDTD appears in timing comparisons only, as the reference rather than an accuracy competitor.",
     "The architecture makes three changes to XPINN: per-subdomain Fourier embeddings (F), the corrected interface treatment (D), and adaptive sampling (A). The ablation removes each in turn, testing five configurations: baseline with none, F only, D only, F and D together, and the full architecture. Everything else is held fixed, including geometry, reference solution, network size, optimizer schedule, and training length, and each configuration runs three times with different random seeds, reported as mean and spread, since single-run PINN results are noisy enough that one number can reflect the initialization rather than the architecture.",
     "In the overall study, the independent variable is which components are active, and the dependent variables are the metrics above, with global and interface-region relative L2 error as the main outcomes and inference time as secondary. The control is the standard PINN and the experimental condition is the full architecture, with the three published methods between them to show whether the combination beats its individual parts, the real claim since none of the three is new alone. Confounders are controlled where possible: random seeds and sampling vary, handled by three seeds and reported spread; hardware affects timing, so timing runs on one machine; and penalty weights and training budget are held constant so no configuration benefits from different weighting or longer training. Two simplifications are acknowledged rather than controlled, the perfect-conductor treatment of copper and the fixed-property model of FR-4, since both simplify the reference and the model equally and so do not bias the comparison, though they limit how directly the absolute error figures carry to a physical PCB."
    ]
   },
   {
    "heading": "References",
    "paragraphs": [
     "[1] Raissi, M., Perdikaris, P., & Karniadakis, G.E. (2019). Physics-informed neural networks: A deep learning framework for solving forward and inverse problems involving nonlinear partial differential equations. Journal of Computational Physics, 378, 686-707.",
     "[2] Jagtap, A.D., & Karniadakis, G.E. (2020). Extended physics-informed neural networks (XPINNs): A generalized space-time domain decomposition based deep learning framework for nonlinear partial differential equations. Communications in Computational Physics, 28(5), 2002-2041.",
     "[3] Tancik, M., Srinivasan, P., Mildenhall, B., et al. (2020). Fourier features let networks learn high frequency functions in low dimensional domains. Advances in Neural Information Processing Systems, 33, 7537-7547.",
     "[4] Wang, S., Wang, H., & Perdikaris, P. (2021). On the eigenvector bias of Fourier feature networks: From regression to solving multi-scale PDEs with physics-informed neural networks. Computer Methods in Applied Mechanics and Engineering, 384, 113938.",
     "[5] Nohra, M., & Dufour, S. (2024). Physics-informed neural networks for the numerical modeling of steady-state and transient electromagnetic problems with discontinuous media. arXiv:2406.04380.",
     "[6] Nohra, M., & Dufour, S. (2024). Approximating electromagnetic fields in discontinuous media using a single physics-informed neural network. arXiv:2407.20833.",
     "[7] Oskooi, A.F., Roundy, D., Ibanescu, M., et al. (2010). MEEP: A flexible free-software package for electromagnetic simulations by the FDTD method. Computer Physics Communications, 181(3), 687-702.",
     "[8] Lu, L., Meng, X., Mao, Z., & Karniadakis, G.E. (2021). DeepXDE: A deep learning library for solving differential equations. SIAM Review, 63(1), 208-228.",
     "[9] Wu, C., Zhu, M., Tan, Q., Kartha, Y., & Lu, L. (2023). A comprehensive study of non-adaptive and residual-based adaptive sampling for physics-informed neural networks. Computer Methods in Applied Mechanics and Engineering, 403, 115671."
    ]
   }
  ]
 }
};
