#!/usr/bin/env python3
"""Bundle content/decks/*.json into js/decks.js.

The slideshow and the methodology reader read their content from a single
script the page loads directly, so the site keeps working from a plain file://
open and needs no fetch, no CORS and no build server.

    python3 tools/build-content.py
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DECKS = ROOT / "content" / "decks"
OUT = ROOT / "js" / "decks.js"

# Which project each methodology write-up belongs to. The PDFs carry no project
# ID, so the mapping is by subject matter (see content/decks/README.md).
METHODOLOGY_OWNERS = {
    "method-pinn-cylinder-flow": "P-12",
    "method-neural-ode-flight": "P-05",
    "method-unnamed": "P-07",
}

# Notes the authors left to themselves in the source documents. They are real
# document content, so the JSON keeps them verbatim — but they are not part of
# the write-up and should not be published.
PLACEHOLDER = re.compile(r"^\s*\[\s*(insert|tbd|todo|note to self)\b", re.I)

dropped = []
rendered = []


def clean(lines, where):
    kept = []
    for line in lines:
        if PLACEHOLDER.match(line):
            dropped.append(f"{where}: {line.strip()[:70]}")
            continue
        kept.append(line)
    return kept


decks = {}
methodologies = {}

for path in sorted(DECKS.glob("*.json")):
    data = json.loads(path.read_text())
    stem = path.stem
    if stem in METHODOLOGY_OWNERS:
        owner = METHODOLOGY_OWNERS[stem]
        sections = []
        for section in data.get("sections", []):
            paragraphs = clean(section.get("paragraphs", []), f"{stem}/{section.get('heading', '')}")
            if not paragraphs and not section.get("heading"):
                continue
            sections.append({"heading": section.get("heading", ""), "paragraphs": paragraphs})
        methodologies[owner] = {
            "source": data.get("source", ""),
            "title": data.get("title", ""),
            "authors": data.get("authors", ""),
            "sections": sections,
        }
    elif re.fullmatch(r"P-\d{2}", stem):
        text_slides = []
        for slide in data.get("slides", []):
            text_slides.append({
                "n": slide.get("n"),
                "title": slide.get("title", ""),
                "body": [line for line in slide.get("body", []) if line and line.strip()],
            })

        # Rendered images of the real deck win over the text rendering. They
        # are authoritative on slide COUNT too (they come from the deck
        # itself, while text boundaries were inferred), so the deck is rebuilt
        # from the images rather than zipped against the text — a count
        # mismatch would otherwise caption slides with the wrong text.
        images = sorted((ROOT / "uploads" / "slides" / stem).glob("*.webp"))
        if images:
            aligned = len(images) == len(text_slides)
            slides = []
            for i, image in enumerate(images):
                slide = {
                    "n": i + 1,
                    "image": f"uploads/slides/{stem}/{image.name}",
                    "title": text_slides[i]["title"] if aligned else "",
                    "body": [],
                }
                slides.append(slide)
            rendered.append(f"{stem}: {len(images)} slide images"
                            + ("" if aligned else " (text not aligned, images only)"))
        else:
            slides = text_slides

        decks[stem] = {
            "source": data.get("source", ""),
            "title": data.get("title", ""),
            "slides": slides,
        }
    else:
        print(f"skipping unrecognised file: {path.name}", file=sys.stderr)

header = (
    "/* Generated by tools/build-content.py from content/decks/*.json — do not edit. */\n"
)
OUT.write_text(
    header
    + "window.PAIRS_DECKS = " + json.dumps(decks, ensure_ascii=False, indent=1) + ";\n"
    + "window.PAIRS_METHODOLOGIES = " + json.dumps(methodologies, ensure_ascii=False, indent=1) + ";\n"
)

print(f"decks: {len(decks)} ({sum(len(d['slides']) for d in decks.values())} slides)")
for line in rendered:
    print("  image slides ->", line)
print(f"methodologies: {len(methodologies)} -> {sorted(methodologies)}")
if dropped:
    print("dropped author placeholders:")
    for line in dropped:
        print("  -", line)
